### ISSUE TITLE
VPN IPv6 connection

### ISSUE THREAD

**Issue by klmhsb42** [syncloud/platform#438]
Could you tell me if VPN app should work with IPv6? I can only access from my private network with IPv4 and can only get IPv4 tunnel through my DSlite even if I choose "combined IPv4/IPv6 Tunnel" in my openVPN andorid app. I can not access from extern IPv6 network. To open port 1194 doesn't help, which I don't need if I understand correctly. openVPN app logs say that the app is trying to connect with _[IPv6]:1194 via UDP_ and _[subdomain.syncloud.it]:1194 (IPv6) via UDPv6_ which both are failing.

**Comment by cyberb** [comment]
Can you run this command:
````
netstat -lnp | grep 1194
````

**Comment by klmhsb42** [comment]
`udp         0         0 0.0.0.0:1194         0.0.0.0:*        3316/openvpn`

**Comment by cyberb** [comment]
Could you try setting Proto to udp6 on Configuration - OpenVPN config page and save?
That should make it listen on both v4 and v6. I will make it default then.

**Comment by klmhsb42** [comment]
Not sure where to run the command or which config file to edit. I ended up here `/snap/openvpn/current/config/openvpn/` but there is only keys folder. Also I tried `apt-cache policy openvpn` but not sure what output means and if it's V2.3 or 2.4. Docs say to run `openvpn --config myvpn.conf` and then `proto udp6`. Version 2.4 should use IPv4 and 6 with just `proto udp` see [here](https://community.openvpn.net/openvpn/wiki/GettingStartedwithOVPN?__cf_chl_jschl_tk__=c39558c85b1f4ba22110b66359c8116af8676355-1578782495-0-AfRRNc5DMpuIWTyf2WNNAbcTy7PzNlg3gAqdlfySAsmw2Q17VHOQWCfrENrgPhWvGBkSyFXC41otUPYASO1Z0PlhLbrVAis69ut49XzxpA9jeoZVJT7Us64qtprmbcHdsukFdChzOCmu2bFCvXWD2dokBNgTPwM_z2u3IoA2KbDXO0PO6xCnb5zYRyhnMWH-UHhxRWfgHB4KxH7xK6IZ9Bgh89KEK2I_Kk-Eet3VRG5z-suHp6PhzI3hTt7Kt1u4QNJcKueb42u_5Opf1DWJ92gQj-TEq90bZc0EWnY5IG1JDZWebceviKu9B5RMm8cm7Q). I will try it if you could give me some help how to do...

**Comment by cyberb** [comment]
The setting is in our OpenVPN UI.

**Comment by klmhsb42** [comment]
Ok that was easy. Andorid app says UDPv6 (sometimes) but ipv6-test.com says IPv6 not supported

**Comment by klmhsb42** [comment]
`netstat -lnp | grep 1194`
`udp6       0      0 :::1194                 :::*                                5591/openvpn`

**Comment by klmhsb42** [comment]
(1) Update to "ipv6-test.com says IPv6 not supported": Works for windows 10 client but not for android app client. [They](https://www.vpnusers.com/viewtopic.php?t=4741) suggest to use _L2-mode OpenVPN_ but I don't know [how to do](https://openvpn.net/vpn-server-resources/how-to-setup-layer-2-ethernet-bridging/). 

(2) I will still have to test it from extern IPv6 network (I'm testing from my home network now) and will let you know if it works.

(3) I'm not able to resolve local hostnames from my router. One solution could be [this](https://steamforge.net/wiki/index.php/How_to_configure_OpenVPN_to_resolve_local_DNS_%26_hostnames) or as [here](https://forums.openvpn.net/viewtopic.php?t=19967) suggested to use _TAP instead of TUN mode_.

**Comment by klmhsb42** [comment]
To (2): access from extern IPv6 network works

**Comment by cyberb** [comment]
What android app says?

**Comment by klmhsb42** [comment]
Same as the windows app. Private IP of device is IPv4. Server is syncloud with IPv6. Port is 1194 and Protocol is UDPv6. Everything is fine. Only strange thing is, that my andorid device doesn't have an IPv6 address anymore if I test it, so I can't access IPv6 only server, which is strange as I have to be in IPv6 network to access VPN. IPv4 of my ISP is shown. So everything works fine, I just don't have IPv6 anymore.

**Comment by cyberb** [comment]
I see, yes I think there should be a way to also enable IPv6 private network, currently it is IPv4.

**Comment by cyberb** [comment]
I have pushed a new fix for IPv6, can you update using this command:
````
snap refresh openvpn --channel=master
````
Then go to openvpn web: Configuration - OpenVPN.config page and without any change hit Save and apply.

Then try to reconnect using Android (Windows) and see if you can visit IPv6 only sites.

**Comment by klmhsb42** [comment]
All done. 
```
nap refresh openvpn --channel=master
openvpn (master) 20011784 from 'syncloud' refreshed
Snap openvpn is no longer tracking master/stable.
```
Android client has time out error. Can not connect anymore. I'm testing from privat network. App logs says, that the client is testing over UDP and UDPv4.

**Comment by klmhsb42** [comment]
I have no IPv6 preference in the andorid app. Setting to IPv4/6 tunnel doesn't make a differnece.

**Comment by klmhsb42** [comment]
Ok, it tries also udpv6. But i cant connect.

**Comment by cyberb** [comment]
Could you send you server config to support:

````
cat /var/snap/openvpn/current/openvpn/server.conf
````

**Comment by klmhsb42** [comment]
Done

**Comment by cyberb** [comment]
Ok, fixed another problem, could you repeat, refresh from master channel and save from UI.
If it does not work please send me server config again.

**Comment by klmhsb42** [comment]
Can not open UI anymore.
```
502 Bad Gateway
nginx/1.13.12
```

```
root@odroid-xu3and4:~# snap refresh openvpn --channel=master
error: cannot perform the following tasks:
- Stop snap "openvpn" services ([start snap.openvpn.web.service snap.openvpn.server.service snap.openvpn.nginx.service] failed with exit status 1: Job for snap.openvpn.server.service failed. See 'systemctl status snap.openvpn.server.service' and 'journalctl -xn' for details.
)
- Start snap "openvpn" (20011885) services ([start snap.openvpn.web.service snap.openvpn.server.service snap.openvpn.nginx.service] failed with exit status 1: Job for snap.openvpn.server.service failed. See 'systemctl status snap.openvpn.server.service' and 'journalctl -xn' for details.
)
```

**Comment by klmhsb42** [comment]
server config per mail done

**Comment by cyberb** [comment]
Ok, previous issue broke ipenvpn installation.
Could you remove first and then refresh:
````
snap remove openvpn
snap refresh openvpn --channel=master
````
Then you will need to generate client key again before you can test connection.

**Comment by klmhsb42** [comment]
Ok all done + save and apply by UI. I can connect again. https://ipv6-test.com/ Still says IPv6 not supported. The client app shows private IP both 4 and 6. Server public is 6. UDPv6.

**Comment by klmhsb42** [comment]
Should I send you clinet logs?

**Comment by cyberb** [comment]
Yes please and server config again.
We are getting there :)

**Comment by klmhsb42** [comment]
done

**Comment by cyberb** [comment]
Now you need to upgrade system from settings first.
Then upgrade openvpn and save config.
Then try connecting again.
If still does not work send me server config please.

**Comment by klmhsb42** [comment]
with Windows Client it works, with Android (Version 7.0) Client still not (IPv6 Test negative). Logs per mail

**Comment by cyberb** [comment]
This is strange, I have tested Syncloud device with IPv6 and OpenVPN Connect on Android v9.1 worked using IPv6 and I was able to browse the internet.
Can you send your server config?
Also a screenshot from Android and logs.

**Comment by klmhsb42** [comment]
I can access from extern IPv6 and browse the internet, too. I just can't open IPv6 only websites anymore (only on my Android v7). I'm testing this from my privat network. I don't know if I have this issue from extern network. Maybe it's an issue of old Android versions. Anyway, it's not that big deal, so if it takes too much time to fix it, we can close this issue...
![vpn_problem](https://user-images.githubusercontent.com/44033489/73133741-40050c00-402d-11ea-8d21-4f24b4150fa7.png)

**Comment by cyberb** [comment]
Interesting, for me is says "your private IPv4" and "your private IPv6".
So I am curious if your phone supports IPv6. At home do you get IPv6 address for the phone when connected to WiFi? You can see it in Settings - System - About phone - Status. If you do not get IPv6 Frome network which support IPv6 that is a phone issue.

**Comment by klmhsb42** [comment]
Left screenshot is without VPN, so I get IPv6. Settings show both 4 and 6 address.

**Comment by klmhsb42** [comment]
Settings sgow actually v6 even with VPN connection. I don't know what's wrong...

**Comment by cyberb** [comment]
VPN client defently does not show IPv6.
You need to test from later android version somehow. Maybe it is openvpn app + old android issue. What version of VPN Connect do you have?

**Comment by klmhsb42** [comment]
Yes, only "server public ip" is v6. VPN Connect v 3.1.0.(4292)

**Comment by klmhsb42** [comment]
If I test it with my Windows 10 PC, it shows the same (private IP as v4) but IPv6 test is positiv

**Comment by cyberb** [comment]
> Yes, only "server public ip" is v6. VPN Connect v 3.1.0.(4292)

I have the same

**Comment by cyberb** [comment]
> If I test it with my Windows 10 PC, it shows the same (private IP as v4) but IPv6 test is positiv

Strange, do you think it even uses VPN for IPv6 then. Can you send you server conf to support:
````
cat /var/snap/openvpn/current/openvpn/server.conf
````

**Comment by klmhsb42** [comment]
done. Well, it's hard to know, as I'm acessing through privat network

**Comment by cyberb** [comment]
Ok, you still have old server config which does not support IPv6.
I have pushed openvpn app to prod so it should be easier.
1. Check that you are on latest platform in settings - updates. Upgrade if needed.
2. Uninstall OpenVPN app and install again so it regenerates server config.
3. Create new client certificate from the UI and try to use it in Android.
You should have both IPv4 and IPv6 private addresses. If not send me your new server config.

**Comment by klmhsb42** [comment]
Ok, now the client shows both IP! like you said. However, IPv6 test fails now with windows 10 too. config per mail

**Comment by klmhsb42** [comment]
The app makes sometime UDPv4 connection, but I test it only if I have UDPv6 connection

**Comment by cyberb** [comment]
Are you testing from local network or external?
What IP versions do you have on external network?

**Comment by klmhsb42** [comment]
Still local. I would have to test it from a friends Wifi. Can I send you my VPN certificate per mail and you test it? Also I'm not sure if I need to open port 1194 for connection. Last time it did only work with open port 1194 (and 80/443) + 
```
Enable PING6 + Open firewall for delegated IPv6 prefixes of this device +
Open this device completely for internet sharing via IPv6 (exposed host)
```
And I don't know what I really need to conect from extern. Without everything it doesn't work and with everything it works from extern. So would be cool if could try it several times to connect while I'm removing settings from my router step-by-step...

**Comment by klmhsb42** [comment]
certificate per mail done

**Comment by klmhsb42** [comment]
maybe [this](https://forum.openwrt.org/t/escaping-dslite-hell-openvpn-via-ipv6/22233/7) could help

**Comment by klmhsb42** [comment]
[this](http://www.thomas--schaefer.de/openvpn-fuer-altlasten.html) could help as well. It's in german but maybe you can translate with chrome browser. I think my problem is the NAT, but not sure...

**Comment by cyberb** [comment]
Forgot to tell you, I tried your certificate. Connection worked, but IPv6 test site said IPv6 is not available. I was trying from dual stack network.

So when you open https://ipv6-test.com/ from home pc does it show that IPv6 is ok?

**Comment by klmhsb42** [comment]
Do you mean without VPN? Then, yes. IPv6 is native and test is green...

**Comment by cyberb** [comment]
> Do you mean without VPN?

Yes

Ok, need to dig more, I had to change my ISP and as a result lost IPv6 which I had for two weeks :)
I will try to setup a device in the cloud to test it.

**Comment by klmhsb42** [comment]
Cool, keep me updated

**Comment by cyberb** [comment]
Can you try new version:
```
snap refresh openvpn --channel=master
```
IPv6 forwarding was not enabled.

**Comment by klmhsb42** [comment]
done + save and apply. IPv6 Test negative. I sent you logs per mail...

**Comment by cyberb** [comment]
Could you run:
```
cat  /proc/sys/net/ipv6/conf/all/forwarding
```
And:
```
ping6 google.con
```
And also send the output of ```ifconfig``` to support.

**Comment by klmhsb42** [comment]
`cat  /proc/sys/net/ipv6/conf/all/forwarding`
output:
`1`
and
`ping6 google.com`
output:
`connect: Network is unreachable`

**Comment by klmhsb42** [comment]
ifconfig per mail

**Comment by cyberb** [comment]
Looks like you do not have IPv6 address on the device.
Could you run this and reboot:
```
echo "iface eth0 inet6 dhcp" >> /etc/network/interfaces
```

**Comment by klmhsb42** [comment]
ok, I did. There is not really a change

`cat /proc/sys/net/ipv6/conf/all/forwarding`
output:
`1`
and
`ping6 google.com`
output:
`connect: Network is unreachable`
ifconfig per mail

**Comment by cyberb** [comment]
Could you run this:
```
cat /etc/network/interfaces
```

**Comment by klmhsb42** [comment]
```
auto lo
iface lo inet loopback

auto eth0
iface eth0 inet dhcp
iface eth0 inet6 dhcp
```

**Comment by cyberb** [comment]
Did you reboot?

**Comment by klmhsb42** [comment]
Yes, via the syncloud platform UI. I could do hard reboot by plugging power cable out/in. Don't know if this would make a difference

**Comment by cyberb** [comment]
Could you remove OpenVPN app and then remove run:
```
ip link delete tun0
```
Then reboot and try ping6.

**Comment by klmhsb42** [comment]
ok, ping6 works now

**Comment by cyberb** [comment]
Could you send me:
```
ip -6 route show
```
Then install openvpn with:
```
snap install openvpn --channel=master
```
Then again:
```
ip -6 route show
```

**Comment by klmhsb42** [comment]
done

**Comment by cyberb** [comment]
Could your remove openvpn and install latest (with no IPv6 routes modification).

```
snap install openvpn --channel=master
```

**Comment by klmhsb42** [comment]
I tested what you sent me per mail, but it didn't work. Sorry, I forgot to answer. Ok, done. Should I try to connect?

**Comment by klmhsb42** [comment]
IPv6 not supported

**Comment by cyberb** [comment]
Could you ping6 from server?
Could you connect with IPv4?
Could you connect with IPv6?
Could you send ```ip -6 route show```?
Could you send ```ifconfig```?

**Comment by klmhsb42** [comment]
Ping6 works. Sent mail. OpenVPN certificate attached in mail. You can try to connect, if you want.

**Comment by cyberb** [comment]
Cannot connect as you now have only local  IPv6 (fe80) on your eth0 network interface.
Just realized your IPv6 is actually local IP (fe80).
Could you remove openvpn and reboot to make sure you actually have anything other than fe80 under inet6 for eth0?

**Comment by klmhsb42** [comment]
see mail with new certificate

**Comment by cyberb** [comment]
Ip looks good.
Still cannot connect to neither 1194 nor 443.
Can you see your device in browser?
Was it visible before installing openvpn?

**Comment by klmhsb42** [comment]
yes, you are right device is not public accesible anymore. ports are open. https://www.syncloud.it/user.html says "IPv6 Address: Not provided"

**Comment by cyberb** [comment]
Right, sorry for so many requests, but I still have no IPv6 for testing. Tried Amazon EC2 instance but they give a single IP instead of 64 bit block like home ISPs usually do.

Was you devise ever accessible by IPv6 from the Internet?

**Comment by klmhsb42** [comment]
As long as I can help, I will answer. Yes it was accessible by IPv6 and yes, it was possible to connect to OpenVPN via IPv6 from extern. Only thing was, that https://ipv6-test.com/ showed that IPv6 is not supported (after connection!). But I was still able to access the web in through the VPN (but by IPv4 only). Could be a NAT problem? 

Now, my IPv6 is removed from https://www.syncloud.it/user.html trough one of the commands. It's ok, as I'm playing arround with the device. Maybe I should activate it again? Otherwhise I could re-flash syncloud, if we don't find the error.

So, at least we could go back to old version. http://www.ipv6proxy.net/ is helpful tool to test at least access, but I don't want to submit any password. I don't have external IPv6 network for testing neither at the moment. Neither from my mobile ISP nor from university or any public place.

**Comment by cyberb** [comment]
>As long as I can help, I will answer. Yes it was accessible by IPv6 and yes, it was possible to connect to OpenVPN via IPv6 from extern. Only thing was, that https://ipv6-test.com/ showed that IPv6 is not supported (after connection!). But I was still able to access the web in through the VPN (but by IPv4 only). Could be a NAT problem?

As I understand you do not need NAT on IPv6, if you have at least a 64 bit prefix IPv6 range (this is a standard for ISP v6 customers). So in the beginning I was following the setup which was using two 64 bit subnets (https://community.openvpn.net/openvpn/wiki/IPv6#Details:IPv6routedblock).

Currently I am trying the second approach (https://community.openvpn.net/openvpn/wiki/IPv6#SplittingasingleroutableIPv6netblock)

In the end I am not even sure what will it achieve, I guess to hide you real location.

>Now, my IPv6 is removed from https://www.syncloud.it/user.html trough one of the commands. It's ok, as I'm playing arround with the device. Maybe I should activate it again? Otherwhise I could re-flash syncloud, if we don't find the error.

I have recently fixed the problem when ipv6 would stay in DNS when it was not available any more on device and caused a lot of problems accessing device from DS network and half of the time trying to connect to non-existent IPv6.
Could you re-flesh so we can start over having a working IPv6 DNS.

>So, at least we could go back to old version. http://www.ipv6proxy.net/ is helpful tool to test at least access, but I don't want to submit any password. I don't have external IPv6 network for testing neither at the moment. Neither from my mobile ISP nor from university or any public place.

I see, so you have ipv6 from your broadband provider? I have ipv6 (DS) only from my mobile provider, so I can test. Let's try to finish this second IPv6 testing option. I can always rollback to version one later.

**Comment by klmhsb42** [comment]
Yes, I have ipv6 from your broadband provider, however as dual stack lite, like [here ](https://www.juniper.net/documentation/en_US/junos/topics/concept/ipv6-dual-stack-lite-overview.html) described. I will let you know, when I've re-fleshed...

**Comment by klmhsb42** [comment]
*my

**Comment by klmhsb42** [comment]
I would like to use my mini linux pc/VM server which is always on for future tests, as it's easier to setup a new VM image. However, I've installed it like 3 months ago, but I still haven't a SSL certificate. I sent my logs to support now. Could you fix that first? I would be able to cooparate on the IPv6 issue then...

**Comment by klmhsb42** [comment]
OK, certificate works now. Let me know what to test for VPN.

**Comment by cyberb** [comment]
Have installed master openvpn?
```
snap install openvpn --channel=master
```

**Comment by klmhsb42** [comment]
I tried it now again. That's the problem at the moment. After installation https://www.syncloud.it/user.html says "IPv6 Address: Not provided" and external access is not possible for me anymore. There must be some error in that openvpn version...

**Comment by klmhsb42** [comment]
Maybe it removes the IPv6 entry by installation, maybe that of eth0? https://device.syncloud.it/network.html shows still the entry

**Comment by cyberb** [comment]
Right, openvpn installation definitely breaks IPv6 somehow.
1. Could you relash and make sure device works again and visible from outside.
2. Send:
```
ip -6 route show
ifconfig
```
3. Install openvpn:
```
snap install openvpn --channel=master
```
4. Send  ip and ifconfig again.

If you are using virtual box you can use snapshots to save VM states to simplify all this.

**Comment by klmhsb42** [comment]
done and mail sent. https://www.syncloud.it/user.html says still "IPv6 Address: Not provided" after restore snapshot. I've to activate it probably again. device was external accessible before.

**Comment by klmhsb42** [comment]
Works after reactivation again.

**Comment by cyberb** [comment]
From the email routes do not look good.
Still before try next thing, can you give me a key to try to connect?

**Comment by klmhsb42** [comment]
I installed it from app store. Domain is still accessible from extern. Could work. certificate per mail.

**Comment by cyberb** [comment]
I can connect but still no access outside, that was expected.
Just published another version with a different subnet mode and a few other things.
Could you repeat the procedure?
Reflash (virtualbox snapshot restore), OpenVPN from master channel, email with ifxonfig and routes.

**Comment by klmhsb42** [comment]
done. I guess there is still something which breaks it. " IPv6 Address: Not provided "

**Comment by cyberb** [comment]
Was it working before you installed OpenVPN?

**Comment by klmhsb42** [comment]
yes, I tried it again, see email. IPv6 (tun0) could be wrong IPv6? https://device.syncloud.it/network.html shows IPv6 entry but https://www.syncloud.it/user.html shows " IPv6 Address: Not provided "

**Comment by cyberb** [comment]
I am running out of ideas on how to make this working with IPv6. I guess routed tun network cannot really work on a single IP block. Another option is a bridged tap network but looks like it needs a more complex setup and allows only a single client on a OpenVPN instance.

**Comment by cyberb** [comment]
Probably wireguard is another popular VPN server to try.

**Comment by thomasschaeferm** [comment]
Hello,
Someone asked me to try this openvpn-solution and to investigate the problem. 
Sorry, it is comment #97 and I did not read the other 96.
First of all: Thank you for this easy-to-use-solution.
At the moment I did just the base installation and installed openvpn via app-center.
It works with payload IPv4 and transport IPv6. (server with ds-lite, client Telekom IPv6-only/NAT64)
IPv6 is configured for payload as well, but IPv6 as payload doesn't work.
In my opinion the mistake is to take the exact same /64-prefix on both ends.
I think there are 3 possible solutions:
1) requesting an additional prefix from the router via dhcpv6-pd 
2) take just a subnet of the /64 and take care to make ndp-proxies
3 take ULU-addresses and do NAT

1. is the clean solution, also preferred/suggested by the openvpn-docs
disadvantage: dhcpv6-pd is not widely support by soho-routers 
2. is a little bit tricky, but it works for me for more than two years
3. is the ugliest solution and should be avoided

4. It would be great, if 1 and 2 are implemented, auto-detection:
if 1 fails then do 2

Thomas

**Comment by cyberb** [comment]
> requesting an additional prefix from the router via dhcpv6-pd

Great I did not know you could do that. Do you need to modify /etc/network/interfaces for that or it is possible to do that dynamically?

**Comment by thomasschaeferm** [comment]
I think it is a dynamic thing. I did not look into the system, how do you configure the network. I just realized, you are using debian8.
Some suggestions: 
- dhclient by ISC with option "-P"
- the networkmanager uses PD implicitly when configured to share IPv6 (method=shared)
- the dhcpcd client with the option ia_pd https://manpages.debian.org/testing/dhcpcd5/dhcpcd.conf.5.en.html#ia_pd

**Comment by thomasschaeferm** [comment]
I looked a little bit in your code. You tried already a mix of splitting the /64 into two /65 and NAT.
Since you have already experience with splitting the network my proposal for a quick solution is to use parts of that code to just separate one /112 out of the /64.
server config
`server-ipv6  2001:db8:5d6:2301:0:0:1:1/112`
system settings
`sysctl net.ipv6.conf.eth0.proxy_ndp=1`
`sysctl net.ipv6.conf.all.forwarding=1`
`ip neigh add proxy 2001:db8:5d6:2301::1:1000 dev eth0`
`ip neigh add proxy 2001:db8:5d6:2301::1:1001 dev eth0` 
`ip neigh add proxy 2001:db8:5d6:2301::1:1002 dev eth0`

(e.g. three clients, for every client you need an additional proxy entry)
This proposal should work. I would also test it for you. At the moment I see only one disadvantage: If a user uses two syncloud boxes with openvpn within one LAN - the duplicate address detection (dad) will detect a problem. Maybe randomizing the start address of /112 could solve this.
PS: This is proposal nr2 from yesterday "take just a subnet of the /64 and take care to make ndp-proxies"
PPS: you can still use `echo 1> /proc/sys/net/ipv6/conf/...` instead of sysctl, depending on your favour

**Comment by cyberb** [comment]
> the dhcpcd client with the option ia_pd https://manpages.debian.org/testing/dhcpcd5/dhcpcd.conf.5.en.html#ia_pd

I like this approach, do you it will not break the network if dhcpv6-pd is not supported on the router?
We have interfaces configured here: https://github.com/syncloud/rootfs/blob/master/bootstrap/files/common/etc/network/interfaces

**Comment by thomasschaeferm** [comment]
dhcp for ipv6 is completely different compared to ipv4. At the moment you ignore ipv6, so it is only configured by slaac, but without dns-resolver. 
The `interfaces` file, you linked, contains the inet6 entry. My fresh install from one of your images doesn't contain that option. 
In future versions you should also find a way to get IPv6-resolvers (usually via SLAAC RFC 8106 and or dhcp-info). 
I found this link:
https://wiki.debian.org/IPv6PrefixDelegation
That means, if you update your base, much things are getting easier.

**Comment by thomasschaeferm** [comment]
If the PD-request fails, nothing should happen - except you can't use the second prefix. 
Then I would recycle parts of the existing prefix, described some comment earlier (/112 with proxy)

**Comment by cyberb** [comment]
I am trying to build new image based on Debian buster with the changes in the above commit. Arm image does not boot yet. Will try x64 image.

**Comment by cyberb** [comment]
Ok here are the images:

x86: https://github.com/syncloud/platform/releases/download/untagged-c3b5b8e9ffe50a63b63f/syncloud-amd64-buster-20.04.img.xz

Odroid HC1/2: https://github.com/syncloud/platform/releases/download/untagged-c3b5b8e9ffe50a63b63f/syncloud-odroid-xu3and4-buster-20.04.img.xz

Network interface has eth1 for a second prefix: https://github.com/syncloud/rootfs/blob/master/bootstrap/files/distro/buster/etc/network/interfaces
Could you boot it and see if you get eth1 up automatically, I am not sure how it should work.

**Comment by thomasschaeferm** [comment]
I get 404.

**Comment by cyberb** [comment]
Sorry, draft was not visible.

x86: https://github.com/syncloud/platform/releases/download/20.04-rc1/syncloud-amd64-buster-20.04.img.xz

Odroid HC1/2: https://github.com/syncloud/platform/releases/download/20.04-rc1/syncloud-odroid-xu3and4-buster-20.04.img.xz

All available here: https://github.com/syncloud/platform/releases/tag/20.04-rc1

**Comment by thomasschaeferm** [comment]
Now with raspi4 image? Or is it a mistake?

**Comment by cyberb** [comment]
What do you mean exactly?
You can get rpi images from here: https://github.com/syncloud/platform/releases/tag/20.04-rc1

**Comment by thomasschaeferm** [comment]
You wrote "Arm image does not boot yet." Is it solved now?

**Comment by cyberb** [comment]
Currently only buster (Debian buster) images have eth1 with prefix delegation. I was not sure if Jessie supports that, but I will try that before the final release.

**Comment by cyberb** [comment]
> You wrote "Arm image does not boot yet." Is it solved now?

It is all good now :) all the boards should work.

**Comment by thomasschaeferm** [comment]
I am little bit confused. Our aim is: to get a prefix (via eth0) and to use that prefix in openvpn.
What is the purpose of eth1? What should I test here? Is eth1 the test interface for requesting a prefix via dhcp-pd or should I connect other devices to eth1 and look, if the devices get an ip of that additional prefix. (like later the openvpn clients?)

**Comment by cyberb** [comment]
Right I am not sure how it should work either.

So the doc said:
>This how-to merely covers requesting a prefix via DHCPv6 on one network interface and assigning that prefix to another.

That is why I thought we need this second interface to hold the second prefix. So later OpenVPN can use it (not done yet). So I thought we can test if our network setup works and it can obtain correctly a prefix.

If you think we do not need eth1, how OpenVPN can obtain a prefix without it? Just by executing DHCP client directly?

**Comment by thomasschaeferm** [comment]
via the "hooks", now I try to start the images...

**Comment by thomasschaeferm** [comment]
After a lot of trouble with the mess of eth0/eth1 (it was not stable, udev-rule did not work...)
and the change from "dhcp" to "auto" -  it works as expected
Now, I think, it is time to change the script in that way, that it doesn't configure an useless eth1, instead it configures "server-ipv6" of the openvpn server



[ip-a.txt](https://github.com/syncloud/platform/files/4465020/ip-a.txt)
[ip-r.txt](https://github.com/syncloud/platform/files/4465021/ip-r.txt)
[jounal.txt](https://github.com/syncloud/platform/files/4465022/jounal.txt)
[dhclient-script.debug.txt](https://github.com/syncloud/platform/files/4465024/dhclient-script.debug.txt)

**Comment by cyberb** [comment]
> After a lot of trouble with the mess of eth0/eth1 (it was not stable, udev-rule did not work...)
> and the change from "dhcp" to "auto" - it works as expected

Re-uploaded x64 and rpi images with the auto fix.

> Now, I think, it is time to change the script in that way, that it doesn't configure an useless eth1, instead it configures "server-ipv6" of the openvpn server

Which script? DHCP? (https://github.com/syncloud/rootfs/blob/master/bootstrap/files/common/etc/dhcp/dhclient-exit-hooks.d/prefix_delegation)

**Comment by thomasschaeferm** [comment]
That script.

**Comment by cyberb** [comment]
Ok, you think I should change the script to do the following things:

1. Add/remove "server-ipv6" according to DHCP event
2. Restart OpenVPN service

And remove eth1.

**Comment by thomasschaeferm** [comment]
Yes, so or similar. Of course not on every event . If prefix is the same, it would not be good to restart openvpn. If the prefix changes, you already lost all clients. Then the ovpn server has to restart.

**Comment by cyberb** [comment]
Ok, removed eth1:
* https://github.com/syncloud/platform/releases/download/20.04-rc1/syncloud-amd64-buster-20.04.img.xz
* https://github.com/syncloud/platform/releases/download/20.04-rc1/syncloud-raspberrypi4-buster-20.04.img.xz

Then install latest OpenVPN:
```
snap refresh openvpn --channel=master
```
It will add this DHCP hook:
https://github.com/syncloud/openvpn/blob/master/bin/prefix_delegation.sh

**Comment by thomasschaeferm** [comment]
After spending some hours of testing: good progress, but it still fails.
The hook-script seems to a problem, which I cannot solve.
`Apr 19 15:20:21 syncloud sh[408]: /sbin/dhclient-script: 7: /etc/dhcp/dhclient-exit-hooks.d/openvpn: [[: not found
Apr 19 15:20:21 syncloud sh[408]: sed: -e expression #1, char 53: unknown option to `s'
`
If I copy manually the prefix (caught by the debug function) and restarting op
[journal-20200419.txt](https://github.com/syncloud/platform/files/4499714/journal-20200419.txt)
[journal-20200419.txt.gz](https://github.com/syncloud/platform/files/4499715/journal-20200419.txt.gz)

envpn, then it works. I had some trouble with other things. For instance, you did not add the IPv4-default route. That confused me a little bit. Another very annoying thing is your dns-handling. 
The openvpn client has often tried to connect to my private IPv4 address. I think it should not published via DNS. It is useless in public IPv4-networks as well in IPv6-only environments.

**Comment by cyberb** [comment]
Fixed the error, please refresh:
```
snap refresh openvpn --channel=master
```

Could you propose fixes to the config as I have tried many things and not sure if it is correct now:

https://github.com/syncloud/openvpn/blob/master/config/web/openvpn-server-config.tpl

**Comment by thomasschaeferm** [comment]
Despite the initial problem ( I have to wait for a prefix change, respectively I have to change the prefix by restarting my router ) the hook script is now running.
But the result doesn't fit to my expectation.  

The right entry is commented by `#` also a space is missing

Sorry for discussion about DNS(*.syncloud.it) and default routes (split tunneling versus complete tunneling) . This should be discussed in separate issues. 
[logfiles.zip](https://github.com/syncloud/platform/files/4504962/logfiles.zip)

**Comment by cyberb** [comment]
Strange, latest version should update it properly.
Could you run this:
```
new_ip6_prefix='2001:123:456::/61' reason='BOUND6' /snap/openvpn/current/bin/prefix_delegation.sh 
```
Then test:
```
cat /var/snap/openvpn/current/openvpn/server.conf | grep server-ip
```
Should print this:
```
server-ipv6 2001:123:456::/61
```

**Comment by thomasschaeferm** [comment]
I did the tests you suggested. 
[logfiles-20200421.zip](https://github.com/syncloud/platform/files/4511340/logfiles-20200421.zip)

**Comment by cyberb** [comment]
Ok apart from not real IPv6 and /61 issue the script seems to set ipv6 correctly and there is no ```#``` or missing space.
So does it actually set real ipv6 when you restart our router?

**Comment by thomasschaeferm** [comment]
If I call it manually (`new_ip6_prefix=...  old_ip6_prefix ....`)  it is correct. But in case of a real prefix change by the router the result is still corrupt. 
At the moment I have no idea. Within the next days I could install the image and the snap master package to my raspberry pi and share my account with you, so you can investigate it. In that case you have to call/email/... me to reconnect the router. I can do that remotely at any time. Your DNS-update is fast enough. The recognition of the prefix change may need 20 minutes or more.
In case you agree, send me your public ssh key. You need IPv6 of course, I have no public IPv4 anymore.

**Comment by cyberb** [comment]
Just pushed another version with some syslogs and a cleanup on disable event (https://github.com/syncloud/openvpn/commit/57dcc7ec1813850cab99a3e4a6937783c6c1f1bf).

Could you refresh:
```
snap refresh openvpn --channel=master
```
Or if it refresh fails
```
snap remove openvpn
snap install openvpn --channel=master
```

Then change router settings and check syslog:
```
root@syncloud:~# grep openvpn-ipv6 /var/log/syslog
Apr 22 12:49:03 syncloud openvpn-ipv6: enable ipv6: 2001:123:456::/64
Apr 22 12:49:05 syncloud openvpn-ipv6: enable ipv6: 2001:123:456::/64
Apr 22 12:49:06 syncloud openvpn-ipv6: enable ipv6: 2001:123:456::/64
```

**Comment by thomasschaeferm** [comment]
The result is:
`grep openvpn-ipv6 /var/log/syslog`
`Apr 22 15:05:45 syncloud openvpn-ipv6: disable ipv6: 2001:a61:576:7efc::/62`
`Apr 22 15:05:45 syncloud openvpn-ipv6: disable ipv6: 2001:a61:5a5:57fc::/62`
[logfiles-20200422.zip](https://github.com/syncloud/platform/files/4517006/logfiles-20200422.zip)

**Comment by thomasschaeferm** [comment]
In the meantime on my raspi:
`Apr 22 18:16:30 syncloud openvpn-ipv6: event reason: BOUND6, new_ip6_prefix: 2001:a61:5a5:57f4::/62, old_ip6_prefix: 2001:a61:5a5:57f4::/62`
`Apr 22 18:16:30 syncloud openvpn-ipv6: event reason: BOUND6, new_ip6_prefix: 2001:a61:5aa:39f4::/62, old_ip6_prefix:`
`Apr 22 18:16:30 syncloud openvpn-ipv6: enable ipv6: 2001:a61:5aa:39f4::/62`

both systems (x86_64, armv7l) use the debian image you provided 3 days ago and 
openvpn snap 
200422110 (x86_64)
200422111 (armv7l)

**Comment by cyberb** [comment]
Sorry I was about to tell you there is a new version with a bit simplified bash if statements and more logs (http://ci.syncloud.org:8080/link/syncloud/openvpn/commit/39ffacd9f503a9739dc47767974ae2b441516421)

You can try in amd64 as well.

**Comment by thomasschaeferm** [comment]
[journals-syslog-amd64-raspi-200422112.zip](https://github.com/syncloud/platform/files/4523878/journals-syslog-amd64-raspi-200422112.zip)

each with two successful prefix changes. But I could not test routing to the client - the prefix length is still wrong.

**Comment by cyberb** [comment]
you get /62 prefix, is this normal?
is this coming from the router?
openvpn says it only supports 64 to 112.

**Comment by thomasschaeferm** [comment]
There is no "normal". Everything is possible between usually /48 and /64. An other device in my network fetches /60 . I don't know if the /62 results by the debian's or my router's preferences. 
Anyway, you can just use the first /64 of whatever you get. The simplest way would be to replace "/*" to "/64"

**Comment by cyberb** [comment]
just push another version with condition-less conversion to 64.
do I need to check if prefix is less then 64 and fail if it is not?

**Comment by thomasschaeferm** [comment]
I am not sure. (RFC are long and practical experience is often a different story ,  https://tools.ietf.org/html/rfc8415 )
I don't expect strange prefix lengths. But it doesn't harm much, if you include a check for the minimum requirements of openvpn (/112) - and if someone in a rare case provides only a /96 or what ever, but enough for an /112 - it shouldn't fail

**Comment by cyberb** [comment]
so I should do something like this probably:
1. if below 64: change to 64
2. if above 112: fail

I should not change 64-112 range (I do right now)

Correct?

**Comment by cyberb** [comment]
done, check latest version.
does ipv6 openvpn actually work now?

**Comment by thomasschaeferm** [comment]
Looks good!  For me it works.  I am not sure, how the initial behavior is - even if the prefix never changes.
[client-android.log](https://github.com/syncloud/platform/files/4529595/client-android.log)
[journal-raspi-200424115.log](https://github.com/syncloud/platform/files/4529597/journal-raspi-200424115.log)
![Screenshot_20200424-162315](https://user-images.githubusercontent.com/6906894/80225489-701f7380-864b-11ea-9404-78e5e31ac0ca.png)
![Screenshot_20200424-162326](https://user-images.githubusercontent.com/6906894/80225498-731a6400-864b-11ea-8da8-a66afe967591.png)
![Screenshot_20200424-162407](https://user-images.githubusercontent.com/6906894/80225508-76155480-864b-11ea-84d2-be87b6e7e536.png)
![Screenshot_20200424-162438](https://user-images.githubusercontent.com/6906894/80225521-79a8db80-864b-11ea-8ec0-d550178ffd8a.png)
![Screenshot_20200424-162505](https://user-images.githubusercontent.com/6906894/80225531-7ca3cc00-864b-11ea-8eee-ced8e70a6b69.png)
![Screenshot_20200424-162902](https://user-images.githubusercontent.com/6906894/80225538-80375300-864b-11ea-802f-592815712e15.png)

**Comment by klmhsb42** [comment]
Nice work. Let me know, if I should test it, too (if I can update from app store). Could you you tell me, what I would have to change in the router settings?

Do I need to check:

 **Additional IPv6 Routers in the Home Network**
[  ] Allow IPv6 prefixes announced by other IPv6 routers in the home network 

And:

**DHCPv6 Server in the Home Network**
(  ) Assign DNS server and IPv6 prefix (IA_PD)

If I would change it, there is also some "warning" _The procedure requires extra confirmation._ which I can confirm by a button on web UI and on the router, I guess. Never done that.

**Comment by thomasschaeferm** [comment]
My pleasure did not last very long. Now I have a problem. I am not sure, if it's on syncloud or my router.

No, do not allow that.
Additional IPv6 Routers in the Home Network
[ ] Allow IPv6 prefixes announced by other IPv6 routers in the home network

That is necessary:
DHCPv6 Server in the Home Network
(*) Assign DNS server and IPv6 prefix (IA_PD)

**Comment by thomasschaeferm** [comment]
Something changed the server.config back to "#server-ipv6"
[journal-raspi.txt](https://github.com/syncloud/platform/files/4529844/journal-raspi.txt)
[syslog.txt](https://github.com/syncloud/platform/files/4529845/syslog.txt)

**Comment by cyberb** [comment]
```
Apr 24 14:46:53 syncloud openvpn-ipv6: event reason: EXPIRE6, new_ip6_prefix: , old_ip6_prefix: ***5f8::/62
Apr 24 14:46:53 syncloud openvpn-ipv6: disable ipv6

Apr 24 14:46:54 syncloud openvpn-ipv6: event reason: RENEW6, new_ip6_prefix: ***:bef8::/62, old_ip6_prefix: ***:bef8::/62

Apr 24 15:16:55 syncloud openvpn-ipv6: event reason: RENEW6, new_ip6_prefix: ***:bef8::/62, old_ip6_prefix: ***:bef8::/62

```

Looks like something else is expired, probably I can save current ip and use it to check what is expiring or changing to not disable randomly.

**Comment by cyberb** [comment]
Another version with the fix for unrelated expiry.

@klmhsb42 Currently this version is on master channel:
```
snap install openvpn --channel=master
```

**Comment by klmhsb42** [comment]
Does work for me only on my Windows10 PC, but not on my android phone (I have IPv6 without VPN connection by WiFi). Client logs to support mail. It's also randomly connecting by IPv6 or local IPv4. However, this doesn't make a difference in the result...

> That is necessary:
> DHCPv6 Server in the Home Network
> (*) Assign DNS server and IPv6 prefix (IA_PD)

I did.

> snap install openvpn --channel=master

I did.

**Comment by cyberb** [comment]
Could you send:
```
grep openvpn-ipv6 /var/log/syslog
```
Are you on latest buster image?

**Comment by klmhsb42** [comment]
> Are you on latest buster image?

Oh, I forgot, do I have to re-install?

**Comment by cyberb** [comment]
Yes as for IPv6 prefix delegation I had to change network configuration which is part of the image.
I would test on a separate device/VM as not all the apps work on buster image yet like diaspora (I am working on it).
New Jessie image will also be there for testing soon (if prefix delegation works on it) but I will probably drop it at some point.

**Comment by klmhsb42** [comment]
Is it still _20.01_ VM image?

**Comment by klmhsb42** [comment]
>     * https://github.com/syncloud/platform/releases/download/20.04-rc1/syncloud-amd64-buster-20.04.img.xz

found it...

**Comment by klmhsb42** [comment]
> drop it at some point

Is it possible to offer Linux version upgrade by the upgrade button for all users? Would be bad if non-technical users would have to reflash and transfer...

**Comment by klmhsb42** [comment]
doesn't work for me on android, see mail

**Comment by klmhsb42** [comment]
but on windows...

**Comment by klmhsb42** [comment]
> doesn't work for me on android, see mail

It worked!!!

**Comment by klmhsb42** [comment]
Don't know what was different in first test. Maybe browser cache... I sent logs

**Comment by klmhsb42** [comment]
In the client app, there was before not distinguished between "your ipv4 and your ipv6" now it is again...

**Comment by klmhsb42** [comment]
I've sent you my openvpn certificate, so you can test from extern...

**Comment by cyberb** [comment]
Used your certificate, IP6 test shows 19/20 (hostname missing)
Cool!

> Is it possible to offer Linux version upgrade by the upgrade button for all users? Would be bad if non-technical users would have to reflash and transfer...

Probably, platform can do this, for now I am trying to make sure all the apps work and image is good to go for new users.

**Comment by klmhsb42** [comment]
> IP6 test shows 19/20 (hostname missing)

is the problem related with this #451 ? There should be the hostname of the ISP, right?

> Cool!

Yes ;)

**Comment by cyberb** [comment]
Closing this as IPv6 seems to work now.
Also platform app contains now the change to network interface for getting IPv6 prefix (should work even on old images)
All on stable channel now.

**Comment by cyberb** [comment]
Some users complain about network not working with current image and new /etc/network/interfaces (https://github.com/syncloud/platform/commit/811b12de7b2811a24d7c74c2630ae8ea9e2dfcc4#diff-2b384cf3a785ebb7fe5f9e411b07092d) file which comes with platform now.
I have tested on my device (ipv4 only network) and it does not break network.
@thomasschaeferm @klmhsb42 Can you test as you have ipv6 network?

1. Download current image (https://github.com/syncloud/platform/wiki)
2. Upgrade system from settings.
3. Check /etc/network/interfaces:
```

**Comment by klmhsb42** [comment]
How can I read _interfaces_?

I've sent you a link per mail to test from extern. I did not reboot yet.

**Comment by thomasschaeferm** [comment]
1. done
2. done
3.
`auto lo`
`iface lo inet loopback`

`allow-hotplug eth0`
`iface eth0 inet dhcp`
`iface eth0 inet6 auto`
`        dhcp 1`
`        request_prefix 1`

**Comment by cyberb** [comment]
> How can I read interfaces?

cat /etc/network/interfaces

**Comment by klmhsb42** [comment]
> cat /etc/network/interfaces

```
auto lo
iface lo inet loopback

allow-hotplug eth0
iface eth0 inet dhcp
iface eth0 inet6 auto
        dhcp 1
        request_prefix 1
```

**Comment by cyberb** [comment]
Good it works for you as well, probably it depends on version of kernel on Odroid C2.

**Comment by klmhsb42** [comment]
Did not need to reboot

**Comment by cyberb** [comment]
@klmhsb42 your device is not actually visible from outside

**Comment by cyberb** [comment]
> Did not need to reboot

You actually need to reboot as it is using old network config still. Again I cannot even see it from outside.

**Comment by klmhsb42** [comment]
ok, I did reboot with _restart_ button. If I use http://ipv6proxy.net website appears just a second and then error 404. I can access from home network

**Comment by cyberb** [comment]
Right, sorry I forgot you have IPv6 only and I tried to open it from my home IPv4. Mobile IPv6 network shows the site, cool.
So the config is fine. Closing this again will check Odroid C2 for kernel updates.

**Comment by thomasschaeferm** [comment]
but openvpn doesn't get the prefix yet, I try to wait a little bit longer

**Comment by thomasschaeferm** [comment]
waiting did not help

**Comment by cyberb** [comment]
Correct, DHCP hook was forgotten in the platform and is available only as part the new images currently. At this moment I will remove network config from the platform and leave it for the image to bring.
The idea of platform brining system configs is not working great on all the images so better leave it as it was for now.

**Comment by cyberb** [comment]
@thomasschaeferm wait a second, DHCP hook is actually part of OpenVPN app and should register automatically, so it is strange that you did not get the prefix. It is probably Jessie issue or something else.

I am trying to release new Buster based images so I will publish a final release in a day or two and hoping you can help me checking if OpenVPN/IPv6 feature is still good there (where it was originally tested).
