### ISSUE TITLE
"Report an issue" is not working

### ISSUE THREAD

**Issue by jpma89** [syncloud/platform#75]
When clicking "Report an issue" on settings.html I get forwarded to error.html. Clicking "Report an issue" there seems not to be working as well. At least I didn't receive a mail.

**Comment by cyberb** [comment]
Do you anything unusual in logs?

**Comment by cyberb** [comment]
Looks like it is server side (redirect) error:

------------------------------------------------------------                                                                                                             [Tue Nov 03 06:28:06.471085 2015] [:error] [pid 11331] Traceback (most recent call last):                       [Tue Nov 03 06:28:06.471109 2015] [:error] [pid 11331]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request                                                                        [Tue Nov 03 06:28:06.471151 2015] [:error] [pid 11331]     rv = self.dispatch_request()                         [Tue Nov 03 06:28:06.471172 2015] [:error] [pid 11331]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request                                                                             [Tue Nov 03 06:28:06.471202 2015] [:error] [pid 11331]     return self.view_functions[rule.endpoint](**req.view_args)                                                                                                           [Tue Nov 03 06:28:06.471222 2015] [:error] [pid 11331]   File "/usr/local/lib/python2.7/dist-packages/flask_cors.py", line 104, in wrapped_function                                                                             [Tue Nov 03 06:28:06.471252 2015] [:error] [pid 11331]     resp = make_response(f(*args, **kwargs))             
[Tue Nov 03 06:28:06.471271 2015] [:error] [pid 11331]   File "/var/www/redirect-prod/redirect/rest.py", line 96, in user_log                                                                                                   [Tue Nov 03 06:28:06.471302 2015] [:error] [pid 11331]     ioc.manager().user_log(request.form)                 
[Tue Nov 03 06:28:06.471321 2015] [:error] [pid 11331]   File "/var/www/redirect-prod/redirect/services.py", line 311, in user_log                                                                                              [Tue Nov 03 06:28:06.471349 2015] [:error] [pid 11331]     self.mail.send_logs(user.email, data)                
[Tue Nov 03 06:28:06.471367 2015] [:error] [pid 11331]   File "/var/www/redirect-prod/redirect/storage.py", line 100, in __exit__                                                                                               [Tue Nov 03 06:28:06.471396 2015] [:error] [pid 11331]     raise exc_val                                        [Tue Nov 03 06:28:06.471427 2015] [:error] [pid 11331] SMTPDataError: (554, 'Message rejected: Email address is not verified.')
[Tue Nov 03 06:28:06.471447 2015] [:error] [pid 11331]

**Comment by vsapronov** [comment]
Fixed now. It was a problem of sending From user address through Amazon SES. Please try to send server logs again now.

**Comment by jpma89** [comment]
Sending issues out of settings.html seems to working now, but sending an issue after being redirected to error.html is still not working for me.


**rest\_public.log**
 
2015-11-04 23:22:30,625 - insider.RedirectConfig - INFO - log file: /opt/data/platform/redirect.cfg
2015-11-04 23:22:32,280 - util - ERROR - {
  "message": "",
  "success": false
}


**nginx\_error.log**

2015/11/04 23:22:32 [warn] 519#0: *91 an upstream response is buffered to a temporary file /opt/app/platform/nginx/uwsgi\_temp/5/00/0000000005 while reading upstream, client: 192.168.0.2, server: localhost, request: "GET /server/html/css/lib/bootstrap-3.3.1.min.css HTTP/1.1", upstream: "uwsgi://unix:///opt/app/platform/config/uwsgi/socket/public.wsgi.sock:", host: "jpbeaglebone1.syncloud.it", referrer: "https://jpbeaglebone1.syncloud.it/server/html/error.html"
2015/11/04 23:22:32 [warn] 519#0: *104 an upstream response is buffered to a temporary file /opt/app/platform/nginx/uwsgi\_temp/6/00/0000000006 while reading upstream, client: 192.168.0.2, server: localhost, request: "GET /server/html/js/lib/jquery-2.1.1.min.js HTTP/1.1", upstream: "uwsgi://unix:///opt/app/platform/config/uwsgi/socket/public.wsgi.sock:", host: "jpbeaglebone1.syncloud.it", referrer: "https://jpbeaglebone1.syncloud.it/server/html/error.html"


**uwsgi\_public.log**

\------------------------------------------------------------

Traceback (most recent call last):
  File "/opt/app/platform/lib/Flask-0.10.1/flask/app.py", line 1475, in full\_dispatch\_request
    rv = self.dispatch\_request()
  File "/opt/app/platform/lib/Flask-0.10.1/flask/app.py", line 1461, in dispatch\_request
    return self.view\_functions\[rule.endpoint](**req.view\_args)
  File "/opt/app/platform/lib/Flask-Login-0.2.11/flask\_login.py", line 758, in decorated\_view
    return func(*args, **kwargs)
  File "/opt/app/platform/lib/syncloud-platform-170/syncloud\_platform/server/rest/public.py", line 240, in send\_log
    RedirectService().send\_log()
  File "/opt/app/platform/lib/syncloud-platform-170/syncloud\_platform/insider/redirect\_service.py", line 37, in send\_log
    util.check\_http\_error(response)
  File "/opt/app/platform/lib/syncloud-platform-170/syncloud\_platform/insider/util.py", line 11, in check\_http\_error
    raise PassthroughJsonError(error.message, response.text)
PassthroughJsonError

\------------------------------------------------------------

[pid: 408|app: 0|req: 22/55] 192.168.0.2 () {46 vars in 1040 bytes} [Wed Nov  4 23:22:30 2015] GET /server/rest/send\_log => generated 15 bytes in 1908 msecs (HTTP/1.1 500) 3 headers in 369 bytes (2 switches on core 1)
[pid: 408|app: 0|req: 23/56] 192.168.0.2 () {46 vars in 1111 bytes} [Wed Nov  4 23:22:32 2015] GET /server/html/error.html => generated 4794 bytes in 30 msecs via sendfile() (HTTP/1.1 200) 8 headers in 616 bytes (0 switches on core 0)
[pid: 408|app: 0|req: 25/57] 192.168.0.2 () {44 vars in 1062 bytes} [Wed Nov  4 23:22:32 2015] GET /server/html/css/lib/bootstrap-3.3.1.min.css => generated 113498 bytes in 175 msecs via sendfile() (HTTP/1.1 200) 8 headers in 620 bytes (0 switches on core 1)
[pid: 509|app: 0|req: 11/58] 192.168.0.2 () {44 vars in 1038 bytes} [Wed Nov  4 23:22:32 2015] GET /server/html/css/form-center.css => generated 608 bytes in 169 msecs via sendfile() (HTTP/1.1 200) 8 headers in 614 bytes (0 switches on core 0)
[pid: 508|app: 0|req: 11/59] 192.168.0.2 () {44 vars in 1037 bytes} [Wed Nov  4 23:22:32 2015] GET /server/html/js/lib/jquery-2.1.1.min.js => generated 84245 bytes in 173 msecs via sendfile() (HTTP/1.1 200) 8 headers in 616 bytes (0 switches on core 0)
[pid: 408|app: 0|req: 26/60] 192.168.0.2 () {44 vars in 1060 bytes} [Wed Nov  4 23:22:32 2015] GET /server/html/css/lib/font-awesome-4.0.3.css => generated 21658 bytes in 191 msecs via sendfile() (HTTP/1.1 200) 8 headers in 618 bytes (0 switches on core 0)
[pid: 510|app: 0|req: 15/61] 192.168.0.2 () {44 vars in 1034 bytes} [Wed Nov  4 23:22:32 2015] GET /server/html/css/main-menu.css => generated 554 bytes in 274 msecs via sendfile() (HTTP/1.1 200) 8 headers in 614 bytes (0 switches on core 0)
[pid: 510|app: 0|req: 15/62] 192.168.0.2 () {44 vars in 1043 bytes} [Wed Nov  4 23:22:32 2015] GET /server/html/js/lib/bootstrap-3.3.1.min.js => generated 35601 bytes in 332 msecs via sendfile() (HTTP/1.1 200) 8 headers in 617 bytes (0 switches on core 1)
[pid: 408|app: 0|req: 27/63] 192.168.0.2 () {44 vars in 1033 bytes} [Wed Nov  4 23:22:32 2015] GET /server/html/js/lib/underscore-min.js => generated 14241 bytes in 203 msecs via sendfile() (HTTP/1.1 200) 8 headers in 616 bytes (0 switches on core 1)
[pid: 508|app: 0|req: 12/64] 192.168.0.2 () {44 vars in 1011 bytes} [Wed Nov  4 23:22:32 2015] GET /server/html/js/android.js => generated 375 bytes in 159 msecs via sendfile() (HTTP/1.1 200) 8 headers in 613 bytes (0 switches on core 1)
[pid: 509|app: 0|req: 13/65] 192.168.0.2 () {44 vars in 1009 bytes} [Wed Nov  4 23:22:32 2015] GET /server/html/js/mobile.js => generated 328 bytes in 176 msecs via sendfile() (HTTP/1.1 200) 8 headers in 612 bytes (0 switches on core 0)
[pid: 509|app: 0|req: 13/66] 192.168.0.2 () {44 vars in 1011 bytes} [Wed Nov  4 23:22:32 2015] GET /server/html/js/lib/URI.js => generated 27598 bytes in 218 msecs via sendfile() (HTTP/1.1 200) 8 headers in 617 bytes (1 switches on core 1)
[pid: 408|app: 0|req: 27/67] 192.168.0.2 () {44 vars in 1007 bytes} [Wed Nov  4 23:22:32 2015] GET /server/html/js/error.js => generated 215 bytes in 135 msecs via sendfile() (HTTP/1.1 200) 8 headers in 612 bytes (0 switches on core 0)
[pid: 510|app: 0|req: 16/68] 192.168.0.2 () {44 vars in 1046 bytes} [Wed Nov  4 23:22:32 2015] GET /server/html/images/logo-52.png => generated 2898 bytes in 65 msecs via sendfile() (HTTP/1.1 200) 8 headers in 602 bytes (0 switches on core 0)
[pid: 510|app: 0|req: 17/69] 192.168.0.2 () {46 vars in 1032 bytes} [Wed Nov  4 23:22:32 2015] GET /server/rest/user => generated 78 bytes in 27 msecs (HTTP/1.1 200) 3 headers in 350 bytes (1 switches on core 1)
[pid: 408|app: 0|req: 28/70] 192.168.0.2 () {46 vars in 1140 bytes} [Wed Nov  4 23:22:32 2015] GET /server/html/css/fonts/glyphicons-halflings-regular.woff => generated 23424 bytes in 31 msecs via sendfile() (HTTP/1.1 200) 8 headers in 616 bytes (0 switches on core 1)

**Comment by cyberb** [comment]
Could let us know if you still have this issue?

**Comment by jpma89** [comment]
I'm not getting forwarded to the error page anymore. I would consider this issue as closed.
