### ISSUE TITLE
ownCloud desktop app receives "Gateway timeout" and "Bad Gateway" under v195 and ownCloud v64

### ISSUE THREAD

**Issue by jpma89** [syncloud/platform#80]
Issue always occurs when trying to sync data via official ownCloud desktop app. Syncloud settings page is not showing any disks after issue occured. Was working fine with v185.

Update: The ownCloud webinterface also reports 504 Gateway Time-out.

**Comment by jpma89** [comment]
**uwsgi_public.log**

[pid: 392|app: 0|req: 63/392] 192.168.0.2 () {46 vars in 1085 bytes} [Sat Nov 28 01:28:07 2015] GET /server/html/settings.html => generated 10801 bytes in 30 msecs via sendfile() (HTTP/1.1 200) 8 headers in 616 bytes (1 switches on core 1)
[pid: 392|app: 0|req: 65/393] 192.168.0.2 () {44 vars in 1014 bytes} [Sat Nov 28 01:28:07 2015] GET /server/html/js/lib/bootstrap-3.3.1.min.js => generated 35601 bytes in 177 msecs via sendfile() (HTTP/1.1 200) 8 headers in 614 bytes (0 switches on core 0)
[pid: 455|app: 0|req: 53/394] 192.168.0.2 () {44 vars in 1008 bytes} [Sat Nov 28 01:28:07 2015] GET /server/html/js/lib/jquery-2.1.1.min.js => generated 84245 bytes in 182 msecs via sendfile() (HTTP/1.1 200) 8 headers in 613 bytes (0 switches on core 1)
[pid: 455|app: 0|req: 53/395] 192.168.0.2 () {44 vars in 1031 bytes} [Sat Nov 28 01:28:07 2015] GET /server/html/css/lib/font-awesome-4.0.3.css => generated 21658 bytes in 199 msecs via sendfile() (HTTP/1.1 200) 8 headers in 615 bytes (0 switches on core 0)
[pid: 458|app: 0|req: 77/396] 192.168.0.2 () {44 vars in 1004 bytes} [Sat Nov 28 01:28:07 2015] GET /server/html/js/lib/underscore-min.js => generated 14241 bytes in 201 msecs via sendfile() (HTTP/1.1 200) 8 headers in 613 bytes (0 switches on core 0)
[pid: 392|app: 0|req: 66/397] 192.168.0.2 () {44 vars in 982 bytes} [Sat Nov 28 01:28:07 2015] GET /server/html/js/lib/URI.js => generated 27598 bytes in 176 msecs via sendfile() (HTTP/1.1 200) 8 headers in 614 bytes (0 switches on core 1)
[pid: 458|app: 0|req: 77/398] 192.168.0.2 () {44 vars in 1033 bytes} [Sat Nov 28 01:28:07 2015] GET /server/html/css/lib/bootstrap-3.3.1.min.css => generated 113498 bytes in 215 msecs via sendfile() (HTTP/1.1 200) 8 headers in 617 bytes (0 switches on core 1)
[pid: 455|app: 0|req: 55/400] 192.168.0.2 () {44 vars in 980 bytes} [Sat Nov 28 01:28:07 2015] GET /server/html/js/mobile.js => generated 328 bytes in 159 msecs via sendfile() (HTTP/1.1 200) 8 headers in 609 bytes (0 switches on core 1)
[pid: 455|app: 0|req: 55/400] 192.168.0.2 () {44 vars in 974 bytes} [Sat Nov 28 01:28:07 2015] GET /server/html/js/sam.js => generated 533 bytes in 136 msecs via sendfile() (HTTP/1.1 200) 8 headers in 609 bytes (0 switches on core 0)
[pid: 458|app: 0|req: 79/401] 192.168.0.2 () {44 vars in 978 bytes} [Sat Nov 28 01:28:07 2015] GET /server/html/js/error.js => generated 215 bytes in 167 msecs via sendfile() (HTTP/1.1 200) 8 headers in 609 bytes (0 switches on core 1)
[pid: 392|app: 0|req: 67/402] 192.168.0.2 () {44 vars in 1005 bytes} [Sat Nov 28 01:28:07 2015] GET /server/html/css/main-menu.css => generated 554 bytes in 208 msecs via sendfile() (HTTP/1.1 200) 8 headers in 611 bytes (0 switches on core 0)
[pid: 392|app: 0|req: 67/403] 192.168.0.2 () {44 vars in 1009 bytes} [Sat Nov 28 01:28:07 2015] GET /server/html/css/form-center.css => generated 608 bytes in 178 msecs via sendfile() (HTTP/1.1 200) 8 headers in 611 bytes (0 switches on core 1)
[pid: 458|app: 0|req: 79/404] 192.168.0.2 () {44 vars in 982 bytes} [Sat Nov 28 01:28:07 2015] GET /server/html/js/android.js => generated 375 bytes in 179 msecs via sendfile() (HTTP/1.1 200) 8 headers in 610 bytes (0 switches on core 0)
[pid: 455|app: 0|req: 57/405] 192.168.0.2 () {44 vars in 1017 bytes} [Sat Nov 28 01:28:07 2015] GET /server/html/images/logo-52.png => generated 2898 bytes in 59 msecs via sendfile() (HTTP/1.1 200) 8 headers in 599 bytes (0 switches on core 1)
[pid: 455|app: 0|req: 57/406] 192.168.0.2 () {44 vars in 984 bytes} [Sat Nov 28 01:28:07 2015] GET /server/html/js/settings.js => generated 2253 bytes in 59 msecs via sendfile() (HTTP/1.1 200) 8 headers in 612 bytes (0 switches on core 0)
[pid: 455|app: 0|req: 58/407] 192.168.0.2 () {46 vars in 1003 bytes} [Sat Nov 28 01:28:07 2015] GET /server/rest/user => generated 78 bytes in 72 msecs (HTTP/1.1 200) 3 headers in 347 bytes (1 switches on core 1)
[pid: 458|app: 0|req: 81/408] 192.168.0.2 () {46 vars in 1043 bytes} [Sat Nov 28 01:28:07 2015] GET /server/rest/settings/external_access => generated 17 bytes in 111 msecs (HTTP/1.1 200) 3 headers in 347 bytes (1 switches on core 1)
[pid: 458|app: 0|req: 81/409] 192.168.0.2 () {46 vars in 1094 bytes} [Sat Nov 28 01:28:07 2015] GET /server/html/css/fonts/glyphicons-halflings-regular.woff => generated 23424 bytes in 94 msecs via sendfile() (HTTP/1.1 200) 8 headers in 613 bytes (0 switches on core 0)
[pid: 392|app: 0|req: 69/410] 192.168.0.2 () {46 vars in 1027 bytes} [Sat Nov 28 01:28:07 2015] GET /server/rest/settings/version => generated 132 bytes in 1075 msecs (HTTP/1.1 200) 3 headers in 348 bytes (1 switches on core 1)




**nginx_error.log**

2015/11/28 01:28:07 [warn] 745#0: *757 an upstream response is buffered to a temporary file /opt/app/platform/nginx/uwsgi_temp/4/03/0000000034 while reading upstream, client: 192.168.0.2, server: localhost, request: "GET /server/html/css/lib/bootstrap-3.3.1.min.css HTTP/1.1", upstream: "uwsgi://unix:///opt/app/platform/config/uwsgi/socket/public.wsgi.sock:", host: "192.168.0.13", referrer: "http://192.168.0.13/server/html/settings.html"

**Comment by cyberb** [comment]
I have tried desktop client and it seems fine.
Could you check disk space, 'df -h' on the device?

**Comment by jpma89** [comment]
Disk is 1.8TB in size and freshly formatted as ext4. The Gateway timeout occurs after some small files.

**Comment by cyberb** [comment]
external disk may be fine, but what about internal memory.
check if df -h shows any 100% use on /dev/mmcblk0p2
````
root@odroid-xu3:~# df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/mmcblk0p2  7.2G  1.9G  5.1G  27% /
udev            745M     0  745M   0% /dev
tmpfs           200M  9.5M  190M   5% /run
tmpfs           996M     0  996M   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           996M     0  996M   0% /sys/fs/cgroup
/dev/sda1       1.8T  233G  1.5T  14% /opt/disk/external
tmpfs           200M     0  200M   0% /run/user/0
````

Also could you check:
/opt/app/owncloud/nginx/logs/error.log
/opt/data/owncloud/owncloud.log
/opt/data/owncloud/php-fpm.log

Also owncloud may be pointing to wrong directory:
/opt/data/owncloud/config/config.php
'datadirectory' setting.

**Comment by cyberb** [comment]
OK, I've got the same issue.
All owncloud services were stopped by some reason.

to check this run:
systemctl owncloud*

Workaround is just to start them:

systemctl start owncloud-postgresql
systemctl start owncloud-php-fpm
systemctl start owncloud-nginx

I will do some testing to see what stopped them.

**Comment by cyberb** [comment]
I think this is the same broken build publisher, which was fixed.
Let's see if that happenes again.

**Comment by jpma89** [comment]
Disk are still not showing up on settings page.

root@beagleboneblack:~# df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/mmcblk0p2  1.9G  999M  823M  55% /
udev             10M     0   10M   0% /dev
tmpfs            99M  4.3M   94M   5% /run
tmpfs           246M  4.0K  246M   1% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           246M     0  246M   0% /sys/fs/cgroup
/dev/sda1       1.8T   70G  1.7T   5% /opt/disk/external
tmpfs            50M     0   50M   0% /run/user/0

**Comment by cyberb** [comment]
Could you post
1. /opt/data/platform/log/rest_public.log
2. lsblk
3. mount

**Comment by jpma89** [comment]
root@beagleboneblack:~# cat /opt/data/platform/log/rest_public.log
2015-11-30 07:00:41,081 - ServerFacade - INFO - ssh command: ssh localhost -p 22 -o StrictHostKeyChecking=no 'nohup /opt/app/sam/bin/sam upgrade platform </dev/null >/dev/null 2>&1 &'
2015-11-30 07:00:41,677 - ServerFacade - INFO -
2015-11-30 19:39:49,502 - events - INFO - /opt/app/platform/bin/on_disk_change.py not found
2015-11-30 19:39:49,514 - systemctl - INFO - checking opt-disk-external.mount
2015-11-30 19:39:49,555 - systemctl - INFO - opt-disk-external.mount: unknown
2015-11-30 19:39:57,306 - systemctl - INFO - enabling opt-disk-external.mount
2015-11-30 19:39:57,820 - systemctl - INFO - starting opt-disk-external.mount
2015-11-30 19:40:04,353 - events - INFO - /opt/app/platform/bin/on_disk_change.py not found
2015-11-30 19:40:47,470 - ServerFacade - INFO - ssh command: ssh localhost -p 22 -o StrictHostKeyChecking=no 'nohup /opt/app/sam/bin/sam install owncloud </dev/null >/dev/null 2>&1 &'
2015-11-30 19:40:47,926 - ServerFacade - INFO -
2015-11-30 19:56:30,430 - events - INFO - /opt/app/platform/bin/on_disk_change.py not found
2015-11-30 19:56:30,443 - systemctl - INFO - checking opt-disk-external.mount
2015-11-30 19:56:30,482 - systemctl - INFO - stopping opt-disk-external.mount
2015-11-30 19:56:30,616 - systemctl - INFO - opt-disk-external.mount: active
2015-11-30 19:56:44,965 - ServerFacade - INFO - ssh command: ssh localhost -p 22 -o StrictHostKeyChecking=no 'nohup /opt/app/sam/bin/sam install owncloud </dev/null >/dev/null 2>&1 &'
2015-11-30 19:56:45,613 - ServerFacade - INFO -
2015-11-30 20:58:03,584 - events - INFO - /opt/app/platform/bin/on_disk_change.py not found
2015-11-30 20:58:03,587 - events - INFO - executing /opt/app/owncloud/bin/on_disk_change.py
2015-11-30 20:58:03,827 - hardware - INFO - fixing permissions on /data/owncloud
2015-11-30 20:58:03,894 - systemctl - INFO - checking opt-disk-external.mount
2015-11-30 20:58:03,936 - systemctl - INFO - opt-disk-external.mount: unknown
2015-11-30 20:58:10,794 - systemctl - INFO - enabling opt-disk-external.mount
2015-11-30 20:58:11,400 - systemctl - INFO - starting opt-disk-external.mount
2015-11-30 20:58:16,671 - events - INFO - /opt/app/platform/bin/on_disk_change.py not found
2015-11-30 20:58:16,673 - events - INFO - executing /opt/app/owncloud/bin/on_disk_change.py
2015-11-30 20:58:16,724 - hardware - INFO - fixing permissions on /data/owncloud
2015-11-30 20:58:16,887 - events - ERROR - error in script, error:
2015-11-30 21:23:13,337 - events - INFO - /opt/app/platform/bin/on_disk_change.py not found
2015-11-30 21:23:13,349 - systemctl - INFO - checking opt-disk-external.mount
2015-11-30 21:23:13,389 - systemctl - INFO - opt-disk-external.mount: failed
2015-11-30 21:23:15,951 - systemctl - INFO - enabling opt-disk-external.mount
2015-11-30 21:23:16,400 - systemctl - INFO - starting opt-disk-external.mount
2015-11-30 21:23:18,120 - events - INFO - /opt/app/platform/bin/on_disk_change.py not found
2015-11-30 21:23:29,165 - ServerFacade - INFO - ssh command: ssh localhost -p 22 -o StrictHostKeyChecking=no 'nohup /opt/app/sam/bin/sam install owncloud </dev/null >/dev/null 2>&1 &'
2015-11-30 21:23:29,622 - ServerFacade - INFO -
2015-12-01 06:44:29,890 - events - INFO - /opt/app/platform/bin/on_disk_change.py not found
2015-12-01 06:44:29,894 - events - INFO - executing /opt/app/owncloud/bin/on_disk_change.py
2015-12-01 06:44:30,659 - hardware - INFO - fixing permissions on /data/owncloud
2015-12-01 06:44:34,096 - events - INFO - /opt/app/platform/bin/on_disk_change.py not found
2015-12-01 06:44:34,099 - events - INFO - executing /opt/app/owncloud/bin/on_disk_change.py
2015-12-01 06:44:34,112 - hardware - INFO - fixing permissions on /data/owncloud
2015-12-01 06:45:09,477 - events - INFO - /opt/app/platform/bin/on_disk_change.py not found
2015-12-01 06:45:09,480 - events - INFO - executing /opt/app/owncloud/bin/on_disk_change.py
2015-12-01 06:45:09,577 - hardware - INFO - fixing permissions on /data/owncloud


------------------

root@beagleboneblack:~# lsblk
NAME         MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sda            8:0    0  1.8T  0 disk
`-sda1         8:1    0  1.8T  0 part /opt/disk/external
mmcblk1boot0 179:16   0    1M  1 disk
mmcblk1boot1 179:24   0    1M  1 disk
mmcblk0      179:0    0  3.7G  0 disk
|-mmcblk0p1  179:1    0   96M  0 part
`-mmcblk0p2  179:2    0    2G  0 part /
mmcblk1      179:8    0  1.8G  0 disk
`-mmcblk1p1  179:9    0  1.8G  0 part



----------------------------

root@beagleboneblack:~# mount
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
udev on /dev type devtmpfs (rw,relatime,size=10240k,nr_inodes=59244,mode=755)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,relatime,size=100508k,mode=755)
/dev/mmcblk0p2 on / type ext4 (rw,noatime,data=ordered)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev)
tmpfs on /run/lock type tmpfs (rw,nosuid,nodev,noexec,relatime,size=5120k)
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,mode=755)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpu,cpuacct)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (rw,nosuid,nodev,noexec,relatime,net_cls,net_prio)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,nodev,noexec,relatime,perf_event)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=22,pgrp=1,timeout=300,minproto=5,maxproto=5,direct)
debugfs on /sys/kernel/debug type debugfs (rw,relatime)
mqueue on /dev/mqueue type mqueue (rw,relatime)
configfs on /sys/kernel/config type configfs (rw,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,relatime)
/dev/sda1 on /opt/disk/external type ext4 (rw,nosuid,nodev,relatime,data=ordered)
tmpfs on /run/user/0 type tmpfs (rw,nosuid,nodev,relatime,size=50256k,mode=700)

**Comment by cyberb** [comment]
everything except this line, looks ok:
````
2015-11-30 21:23:13,389 - systemctl - INFO - opt-disk-external.mount: failed
````
could you run?
````
systemctl --no-page -t service,mount -a | grep "platform\|owncloud\|opt"
````

Also if you do not mind to give me ssh access to the device, I can check what is wrong by myself.

It would be really useful to understand why it stopped working and fix the issue, but at the same time if you need working version quickly, I would re flash it with latest image again.

**Comment by jpma89** [comment]
![syncloud](https://cloud.githubusercontent.com/assets/7020468/11620446/44f54dbe-9cb3-11e5-9437-e0ece4407168.jpg)

**Comment by cyberb** [comment]
Ok, here is another test, could you do the following:
Run platform python:
````
/opt/app/platform/python/bin/python
```
And then run this python code by pasting it into python console:
```
import site
site.addsitedir('/opt/app/platform/lib')
from syncloud_app import logger
from syncloud_platform.tools.hardware import Hardware
logger.init(console=True)
map(str, Hardware().available_disks())
````

It should print something like this (my odroid):
````
root@odroid-xu3:~# /opt/app/platform/python/bin/python
Python 2.7.10 (default, Nov  1 2015, 11:18:49) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import site
>>> site.addsitedir('/opt/app/platform/lib')
>>> from syncloud_app import logger
>>> from syncloud_platform.tools.hardware import Hardware
>>> logger.init(console=True)
>>> map(str, Hardware().available_disks())
['My: /dev/sda1, 1.8T, /opt/disk/external, True']
````

**Comment by cyberb** [comment]
Sorry, forgot to say, this has to be run on Platform v212 or greater.

**Comment by jpma89** [comment]
Found out an interesting thing: Disk disappears during ownCloud installation.

Here are the steps I performed:

Upgrading to v212
Rebooting the device

Disk is running (HDD led on or flashing)
Disk is shown on settings page

root@beagleboneblack:~# /opt/app/platform/python/bin/python
Python 2.7.10 (default, Nov  1 2015, 11:18:49) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import site
>>> site.addsitedir('/opt/app/platform/lib')
>>> from syncloud_app import logger
>>> from syncloud_platform.tools.hardware import Hardware
>>> logger.init(console=True)
>>> map(str, Hardware().available_disks())
['External: /dev/sda1, 1.8T, /opt/disk/external, True', ': /dev/mmcblk1p1, 1.8G, , False']

Starting ownCloud installation via App Store page
Installation starts normally disk is running (HDD led on or flashing)


After a couple of minutes:

Disk not running anymore (HDD led is off)
python.bin processes stop running
Installation fails on UI
No disks shown anymore on settings page

root@beagleboneblack:~# /opt/app/platform/python/bin/python
Python 2.7.10 (default, Nov  1 2015, 11:18:49) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import site
>>> site.addsitedir('/opt/app/platform/lib')
>>> from syncloud_app import logger
>>> from syncloud_platform.tools.hardware import Hardware
>>> logger.init(console=True)
>>> map(str, Hardware().available_disks())

// Did not return, so I pressed CTRL+C //

^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/app/platform/lib/syncloud-platform-212/syncloud_platform/tools/hardware.py", line 24, in available_disks
    lsblk_output = check_output('lsblk -Pp -o NAME,SIZE,TYPE,MOUNTPOINT,PARTTYPE,MODEL', shell=True)
  File "/opt/app/platform/python/lib/python2.7/subprocess.py", line 567, in check_output
    output, unused_err = process.communicate()
  File "/opt/app/platform/python/lib/python2.7/subprocess.py", line 791, in communicate
    stdout = _eintr_retry_call(self.stdout.read)
  File "/opt/app/platform/python/lib/python2.7/subprocess.py", line 476, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt
>>> 
root@beagleboneblack:~#

**Comment by cyberb** [comment]
Do you have dedicated power source for your disk? This is usual issue when disk is under load it will not work stable or switch off if it has not enough power.
Check disk messages in dmesg.

**Comment by jpma89** [comment]
dmesg:

[  334.155174] musb-hdrc musb-hdrc.1.auto: otg: usb_otg_kick_fsm: invalid host/gadget device
[  334.275149] usb 1-1: reset high-speed USB device number 2 using musb-hdrc
[  538.122858] musb-hdrc musb-hdrc.1.auto: otg: usb_otg_kick_fsm: invalid host/gadget device
[  538.262823] usb 1-1: reset high-speed USB device number 2 using musb-hdrc
[  722.669407] INFO: task scsi_eh_0:208 blocked for more than 120 seconds.
[  722.676209]       Not tainted 3.14.42-ti-r64 #1
[  722.684145] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[  722.695982] scsi_eh_0       D c08dd648     0   208      2 0x00000000
[  722.696023] Backtrace: 
[  722.696063] [<c08dd2fc>] (__schedule) from [<c08ddbc4>] (schedule+0x40/0x90)
[  722.696076]  r10:c0df50e0 r9:dc19ef40 r8:dccf3c08 r7:00000002 r6:ffffffff r5:dccf3c04
[  722.696100]  r4:dccf3c00
[  722.696117] [<c08ddb84>] (schedule) from [<c08ddf5c>] (schedule_preempt_disabled+0x20/0x2c)
[  722.696135] [<c08ddf3c>] (schedule_preempt_disabled) from [<c08dfa68>] (__mutex_lock_slowpath+0x170/0x24c)
[  722.696151] [<c08df8f8>] (__mutex_lock_slowpath) from [<c08dfb9c>] (mutex_lock+0x58/0x5c)
[  722.696158]  r10:c0df50e0 r9:dc1a3f18 r8:dc1a3f0c r7:dc1b6800 r6:dc194c40 r5:dccf3800
[  722.696180]  r4:dccf3c00
[  722.696206] [<c08dfb44>] (mutex_lock) from [<c06aa580>] (device_reset+0x28/0x54)
[  722.696213]  r4:dccf3c00 r3:dc1b6800
[  722.696242] [<c06aa558>] (device_reset) from [<c05eaa9c>] (scsi_try_bus_device_reset+0x34/0x68)
[  722.696249]  r5:dccf3800 r4:dc194c40
[  722.696269] [<c05eaa68>] (scsi_try_bus_device_reset) from [<c05ec8bc>] (scsi_eh_ready_devs+0x2c4/0xba8)
[  722.696277]  r4:dc1a3f18 r3:00000000
[  722.696297] [<c05ec5f8>] (scsi_eh_ready_devs) from [<c05ee780>] (scsi_error_handler+0x56c/0x7d4)
[  722.696305]  r10:c0df50e0 r9:dc1a3f18 r8:dc1a2000 r7:dccf3800 r6:dc1a3f0c r5:dc1a3f18
[  722.696327]  r4:dc194c40
[  722.696346] [<c05ee214>] (scsi_error_handler) from [<c0068334>] (kthread+0xd4/0xf0)
[  722.696354]  r10:00000000 r9:00000000 r8:00000000 r7:c05ee214 r6:dccf3800 r5:dc183600
[  722.696376]  r4:00000000
[  722.696397] [<c0068260>] (kthread) from [<c000f698>] (ret_from_fork+0x14/0x20)
[  722.696405]  r7:00000000 r6:00000000 r5:c0068260 r4:dc183600
[  722.696429] INFO: task usb-storage:210 blocked for more than 120 seconds.
[  722.712142]       Not tainted 3.14.42-ti-r64 #1
[  722.721275] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[  722.734163] usb-storage     D c08dd648     0   210      2 0x00000000
[  722.734205] Backtrace: 
[  722.734245] [<c08dd2fc>] (__schedule) from [<c08ddbc4>] (schedule+0x40/0x90)
[  722.734258]  r10:c0cb8508 r9:00000000 r8:00000000 r7:c08de538 r6:7fffffff r5:7fffffff
[  722.734281]  r4:dccf3cb4
[  722.734297] [<c08ddb84>] (schedule) from [<c08dcc8c>] (schedule_timeout+0x19c/0x294)
[  722.734315] [<c08dcaf0>] (schedule_timeout) from [<c08de538>] (wait_for_common+0xb8/0x15c)
[  722.734323]  r10:00000002 r9:00000000 r8:00000000 r7:dc1ee000 r6:7fffffff r5:dccf3cb0
[  722.734344]  r4:dccf3cb4
[  722.734360] [<c08de480>] (wait_for_common) from [<c08de5fc>] (wait_for_completion+0x20/0x24)
[  722.734368]  r10:c0d51f38 r9:00000000 r8:0000001e r7:dccf3c98 r6:00000000 r5:dccf3cb0
[  722.734390]  r4:dccf3c90
[  722.734418] [<c08de5dc>] (wait_for_completion) from [<c066e648>] (usb_sg_wait+0x108/0x198)
[  722.734445] [<c066e540>] (usb_sg_wait) from [<c06ab034>] (usb_stor_bulk_transfer_sglist+0x9c/0xf4)
[  722.734453]  r10:dc1efe14 r8:0001e000 r7:dccf3c28 r6:dccf3c90 r5:c0010200 r4:dccf3c00
[  722.734483] [<c06aaf98>] (usb_stor_bulk_transfer_sglist) from [<c06ab0c0>] (usb_stor_bulk_srb+0x34/0x4c)
[  722.734491]  r10:de04200f r8:0000001f r7:0001e000 r6:dc194c40 r5:dccf3c00 r4:dc194c40
[  722.734520] [<c06ab08c>] (usb_stor_bulk_srb) from [<c06ab1f8>] (usb_stor_Bulk_transport+0x120/0x360)
[  722.734528]  r4:de042000
[  722.734544] [<c06ab0d8>] (usb_stor_Bulk_transport) from [<c06aba08>] (usb_stor_invoke_transport+0x3c/0x460)
[  722.734551]  r10:dccf3c28 r8:c0cb8508 r7:c0cb8508 r6:00000000 r5:dc194c40 r4:dccf3c00
[  722.734582] [<c06ab9cc>] (usb_stor_invoke_transport) from [<c06aa948>] (usb_stor_transparent_scsi_command+0x18/0x1c)
[  722.734589]  r10:dccf3c28 r9:00000000 r8:c0cb20c0 r7:c0cb8508 r6:00000000 r5:dccf3ccc
[  722.734611]  r4:dccf3c00
[  722.734628] [<c06aa930>] (usb_stor_transparent_scsi_command) from [<c06ace84>] (usb_stor_control_thread+0x15c/0x258)
[  722.734646] [<c06acd28>] (usb_stor_control_thread) from [<c0068334>] (kthread+0xd4/0xf0)
[  722.734654]  r10:00000000 r8:00000000 r7:c06acd28 r6:dccf3c00 r5:dc183540 r4:00000000
[  722.734690] [<c0068260>] (kthread) from [<c000f698>] (ret_from_fork+0x14/0x20)
[  722.734698]  r7:00000000 r6:00000000 r5:c0068260 r4:dc183540
[  722.734725] INFO: task jbd2/sda1-8:301 blocked for more than 120 seconds.
[  722.752125]       Not tainted 3.14.42-ti-r64 #1
[  722.760497] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[  722.772540] jbd2/sda1-8     D c08dd648     0   301      2 0x00000000
[  722.772575] Backtrace: 
[  722.772616] [<c08dd2fc>] (__schedule) from [<c08ddbc4>] (schedule+0x40/0x90)
[  722.772627]  r10:dcfbc064 r9:dd76de00 r8:c008a120 r7:dcf9be84 r6:dcf9be78 r5:00000000
[  722.772651]  r4:dcf9a000
[  722.772673] [<c08ddb84>] (schedule) from [<c023832c>] (jbd2_journal_commit_transaction+0x248/0x1aa4)
[  722.772693] [<c02380e4>] (jbd2_journal_commit_transaction) from [<c023e988>] (kjournald2+0xc0/0x258)
[  722.772701]  r10:dcfbc04c r9:c0d9fdf8 r8:dcfbc230 r7:dcf9a000 r6:00000000 r5:dcfbc014
[  722.772723]  r4:dcfbc000
[  722.772742] [<c023e8c8>] (kjournald2) from [<c0068334>] (kthread+0xd4/0xf0)
[  722.772750]  r10:00000000 r9:00000000 r8:00000000 r7:c023e8c8 r6:dcfbc000 r5:dc1d3a00
[  722.772771]  r4:00000000
[  722.772793] [<c0068260>] (kthread) from [<c000f698>] (ret_from_fork+0x14/0x20)
[  722.772801]  r7:00000000 r6:00000000 r5:c0068260 r4:dc1d3a00
[  722.772825] INFO: task ext4lazyinit:305 blocked for more than 120 seconds.
[  722.786513]       Not tainted 3.14.42-ti-r64 #1
[  722.794934] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[  722.806693] ext4lazyinit    D c08dd648     0   305      2 0x00000000
[  722.806735] Backtrace: 
[  722.806776] [<c08dd2fc>] (__schedule) from [<c08ddbc4>] (schedule+0x40/0x90)
[  722.806790]  r10:c0cb8508 r9:00000000 r8:00000002 r7:c08de0bc r6:dc1fc000 r5:7fffffff
[  722.806813]  r4:df9b84a8
[  722.806828] [<c08ddb84>] (schedule) from [<c08dcc8c>] (schedule_timeout+0x19c/0x294)
[  722.806843] [<c08dcaf0>] (schedule_timeout) from [<c08de0bc>] (io_schedule_timeout+0xac/0x11c)
[  722.806851]  r10:dc1fde0c r9:00000000 r8:00000002 r7:7fffffff r6:dc1fc000 r5:df9b7fc0
[  722.806873]  r4:df9b84a8
[  722.806891] [<c08de010>] (io_schedule_timeout) from [<c08de74c>] (wait_for_common_io.constprop.1+0x94/0x118)
[  722.806899]  r7:dc1fc000 r6:7fffffff r5:dc1fddfc r4:dc1fde00
[  722.806925] [<c08de6b8>] (wait_for_common_io.constprop.1) from [<c08de808>] (wait_for_completion_io+0x1c/0x20)
[  722.806933]  r8:00000000 r7:00000000 r6:dc1a9f00 r5:00000000 r4:00000000
[  722.806965] [<c08de7ec>] (wait_for_completion_io) from [<c04a2f3c>] (__blkdev_issue_zeroout+0x1bc/0x1c0)
[  722.806979] [<c04a2d80>] (__blkdev_issue_zeroout) from [<c04a3000>] (blkdev_issue_zeroout+0xc0/0xd4)
[  722.806987]  r10:00000050 r9:00000000 r8:8c000100 r7:00000000 r6:00001000 r5:c0cb8508
[  722.807008]  r4:dd662080
[  722.807027] [<c04a2f40>] (blkdev_issue_zeroout) from [<c01e893c>] (ext4_init_inode_table+0x18c/0x370)
[  722.807035]  r10:da081668 r9:dba4c000 r8:00002300 r7:dcf89400 r6:dcf89800 r5:00000050
[  722.807057]  r4:11800020
[  722.807084] [<c01e87b0>] (ext4_init_inode_table) from [<c0207f98>] (ext4_lazyinit_thread+0x110/0x2bc)
[  722.807091]  r10:3ffffffe r9:c0cb20c0 r8:dc1d38c4 r7:dc1d388c r6:00003a39 r5:dcf89400
[  722.807113]  r4:00002300
[  722.807132] [<c0207e88>] (ext4_lazyinit_thread) from [<c0068334>] (kthread+0xd4/0xf0)
[  722.807139]  r10:00000000 r9:00000000 r8:00000000 r7:c0207e88 r6:dc1d38c0 r5:dd9c1b40
[  722.807161]  r4:00000000
[  722.807183] [<c0068260>] (kthread) from [<c000f698>] (ret_from_fork+0x14/0x20)
[  722.807190]  r7:00000000 r6:00000000 r5:c0068260 r4:dd9c1b40
[  842.813691] INFO: task scsi_eh_0:208 blocked for more than 120 seconds.
[  842.820471]       Not tainted 3.14.42-ti-r64 #1
[  842.827225] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[  842.836702] scsi_eh_0       D c08dd648     0   208      2 0x00000000
[  842.836735] Backtrace: 
[  842.836775] [<c08dd2fc>] (__schedule) from [<c08ddbc4>] (schedule+0x40/0x90)
[  842.836787]  r10:c0df50e0 r9:dc19ef40 r8:dccf3c08 r7:00000002 r6:ffffffff r5:dccf3c04
[  842.836810]  r4:dccf3c00
[  842.836828] [<c08ddb84>] (schedule) from [<c08ddf5c>] (schedule_preempt_disabled+0x20/0x2c)
[  842.836846] [<c08ddf3c>] (schedule_preempt_disabled) from [<c08dfa68>] (__mutex_lock_slowpath+0x170/0x24c)
[  842.836862] [<c08df8f8>] (__mutex_lock_slowpath) from [<c08dfb9c>] (mutex_lock+0x58/0x5c)
[  842.836869]  r10:c0df50e0 r9:dc1a3f18 r8:dc1a3f0c r7:dc1b6800 r6:dc194c40 r5:dccf3800
[  842.836891]  r4:dccf3c00
[  842.836917] [<c08dfb44>] (mutex_lock) from [<c06aa580>] (device_reset+0x28/0x54)
[  842.836925]  r4:dccf3c00 r3:dc1b6800
[  842.836954] [<c06aa558>] (device_reset) from [<c05eaa9c>] (scsi_try_bus_device_reset+0x34/0x68)
[  842.836962]  r5:dccf3800 r4:dc194c40
[  842.836982] [<c05eaa68>] (scsi_try_bus_device_reset) from [<c05ec8bc>] (scsi_eh_ready_devs+0x2c4/0xba8)
[  842.836989]  r4:dc1a3f18 r3:00000000
[  842.837009] [<c05ec5f8>] (scsi_eh_ready_devs) from [<c05ee780>] (scsi_error_handler+0x56c/0x7d4)
[  842.837017]  r10:c0df50e0 r9:dc1a3f18 r8:dc1a2000 r7:dccf3800 r6:dc1a3f0c r5:dc1a3f18
[  842.837039]  r4:dc194c40
[  842.837058] [<c05ee214>] (scsi_error_handler) from [<c0068334>] (kthread+0xd4/0xf0)
[  842.837065]  r10:00000000 r9:00000000 r8:00000000 r7:c05ee214 r6:dccf3800 r5:dc183600
[  842.837087]  r4:00000000
[  842.837109] [<c0068260>] (kthread) from [<c000f698>] (ret_from_fork+0x14/0x20)
[  842.837116]  r7:00000000 r6:00000000 r5:c0068260 r4:dc183600
[  842.837140] INFO: task usb-storage:210 blocked for more than 120 seconds.
[  842.850467]       Not tainted 3.14.42-ti-r64 #1
[  842.856176] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[  842.864959] usb-storage     D c08dd648     0   210      2 0x00000000
[  842.864987] Backtrace: 
[  842.865023] [<c08dd2fc>] (__schedule) from [<c08ddbc4>] (schedule+0x40/0x90)
[  842.865034]  r10:c0cb8508 r9:00000000 r8:00000000 r7:c08de538 r6:7fffffff r5:7fffffff
[  842.865057]  r4:dccf3cb4
[  842.865073] [<c08ddb84>] (schedule) from [<c08dcc8c>] (schedule_timeout+0x19c/0x294)
[  842.865089] [<c08dcaf0>] (schedule_timeout) from [<c08de538>] (wait_for_common+0xb8/0x15c)
[  842.865097]  r10:00000002 r9:00000000 r8:00000000 r7:dc1ee000 r6:7fffffff r5:dccf3cb0
[  842.865119]  r4:dccf3cb4
[  842.865135] [<c08de480>] (wait_for_common) from [<c08de5fc>] (wait_for_completion+0x20/0x24)
[  842.865142]  r10:c0d51f38 r9:00000000 r8:0000001e r7:dccf3c98 r6:00000000 r5:dccf3cb0
[  842.865164]  r4:dccf3c90
[  842.865192] [<c08de5dc>] (wait_for_completion) from [<c066e648>] (usb_sg_wait+0x108/0x198)
[  842.865219] [<c066e540>] (usb_sg_wait) from [<c06ab034>] (usb_stor_bulk_transfer_sglist+0x9c/0xf4)
[  842.865227]  r10:dc1efe14 r8:0001e000 r7:dccf3c28 r6:dccf3c90 r5:c0010200 r4:dccf3c00
[  842.865257] [<c06aaf98>] (usb_stor_bulk_transfer_sglist) from [<c06ab0c0>] (usb_stor_bulk_srb+0x34/0x4c)
[  842.865264]  r10:de04200f r8:0000001f r7:0001e000 r6:dc194c40 r5:dccf3c00 r4:dc194c40
[  842.865294] [<c06ab08c>] (usb_stor_bulk_srb) from [<c06ab1f8>] (usb_stor_Bulk_transport+0x120/0x360)
[  842.865301]  r4:de042000
[  842.865318] [<c06ab0d8>] (usb_stor_Bulk_transport) from [<c06aba08>] (usb_stor_invoke_transport+0x3c/0x460)
[  842.865325]  r10:dccf3c28 r8:c0cb8508 r7:c0cb8508 r6:00000000 r5:dc194c40 r4:dccf3c00
[  842.865356] [<c06ab9cc>] (usb_stor_invoke_transport) from [<c06aa948>] (usb_stor_transparent_scsi_command+0x18/0x1c)
[  842.865364]  r10:dccf3c28 r9:00000000 r8:c0cb20c0 r7:c0cb8508 r6:00000000 r5:dccf3ccc
[  842.865385]  r4:dccf3c00
[  842.865402] [<c06aa930>] (usb_stor_transparent_scsi_command) from [<c06ace84>] (usb_stor_control_thread+0x15c/0x258)
[  842.865420] [<c06acd28>] (usb_stor_control_thread) from [<c0068334>] (kthread+0xd4/0xf0)
[  842.865428]  r10:00000000 r8:00000000 r7:c06acd28 r6:dccf3c00 r5:dc183540 r4:00000000
[  842.865464] [<c0068260>] (kthread) from [<c000f698>] (ret_from_fork+0x14/0x20)
[  842.865471]  r7:00000000 r6:00000000 r5:c0068260 r4:dc183540
[  842.865497] INFO: task jbd2/sda1-8:301 blocked for more than 120 seconds.
[  842.872432]       Not tainted 3.14.42-ti-r64 #1
[  842.883745] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[  842.891743] jbd2/sda1-8     D c08dd648     0   301      2 0x00000000
[  842.891762] Backtrace: 
[  842.891795] [<c08dd2fc>] (__schedule) from [<c08ddbc4>] (schedule+0x40/0x90)
[  842.891803]  r10:dcfbc064 r9:dd76de00 r8:c008a120 r7:dcf9be84 r6:dcf9be78 r5:00000000
[  842.891826]  r4:dcf9a000
[  842.891849] [<c08ddb84>] (schedule) from [<c023832c>] (jbd2_journal_commit_transaction+0x248/0x1aa4)
[  842.891869] [<c02380e4>] (jbd2_journal_commit_transaction) from [<c023e988>] (kjournald2+0xc0/0x258)
[  842.891876]  r10:dcfbc04c r9:c0d9fdf8 r8:dcfbc230 r7:dcf9a000 r6:00000000 r5:dcfbc014
[  842.891899]  r4:dcfbc000
[  842.891916] [<c023e8c8>] (kjournald2) from [<c0068334>] (kthread+0xd4/0xf0)
[  842.891924]  r10:00000000 r9:00000000 r8:00000000 r7:c023e8c8 r6:dcfbc000 r5:dc1d3a00
[  842.891945]  r4:00000000
[  842.891966] [<c0068260>] (kthread) from [<c000f698>] (ret_from_fork+0x14/0x20)
[  842.891973]  r7:00000000 r6:00000000 r5:c0068260 r4:dc1d3a00
[  842.891996] INFO: task ext4lazyinit:305 blocked for more than 120 seconds.
[  842.903351]       Not tainted 3.14.42-ti-r64 #1
[  842.908758] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[  842.917501] ext4lazyinit    D c08dd648     0   305      2 0x00000000
[  842.917529] Backtrace: 
[  842.917563] [<c08dd2fc>] (__schedule) from [<c08ddbc4>] (schedule+0x40/0x90)
[  842.917574]  r10:c0cb8508 r9:00000000 r8:00000002 r7:c08de0bc r6:dc1fc000 r5:7fffffff
[  842.917596]  r4:df9b84a8
[  842.917612] [<c08ddb84>] (schedule) from [<c08dcc8c>] (schedule_timeout+0x19c/0x294)
[  842.917627] [<c08dcaf0>] (schedule_timeout) from [<c08de0bc>] (io_schedule_timeout+0xac/0x11c)
[  842.917635]  r10:dc1fde0c r9:00000000 r8:00000002 r7:7fffffff r6:dc1fc000 r5:df9b7fc0
[  842.917657]  r4:df9b84a8
[  842.917675] [<c08de010>] (io_schedule_timeout) from [<c08de74c>] (wait_for_common_io.constprop.1+0x94/0x118)
[  842.917683]  r7:dc1fc000 r6:7fffffff r5:dc1fddfc r4:dc1fde00
[  842.917709] [<c08de6b8>] (wait_for_common_io.constprop.1) from [<c08de808>] (wait_for_completion_io+0x1c/0x20)
[  842.917717]  r8:00000000 r7:00000000 r6:dc1a9f00 r5:00000000 r4:00000000
[  842.917749] [<c08de7ec>] (wait_for_completion_io) from [<c04a2f3c>] (__blkdev_issue_zeroout+0x1bc/0x1c0)
[  842.917762] [<c04a2d80>] (__blkdev_issue_zeroout) from [<c04a3000>] (blkdev_issue_zeroout+0xc0/0xd4)
[  842.917770]  r10:00000050 r9:00000000 r8:8c000100 r7:00000000 r6:00001000 r5:c0cb8508
[  842.917792]  r4:dd662080
[  842.917811] [<c04a2f40>] (blkdev_issue_zeroout) from [<c01e893c>] (ext4_init_inode_table+0x18c/0x370)
[  842.917819]  r10:da081668 r9:dba4c000 r8:00002300 r7:dcf89400 r6:dcf89800 r5:00000050
[  842.917840]  r4:11800020
[  842.917866] [<c01e87b0>] (ext4_init_inode_table) from [<c0207f98>] (ext4_lazyinit_thread+0x110/0x2bc)
[  842.917874]  r10:3ffffffe r9:c0cb20c0 r8:dc1d38c4 r7:dc1d388c r6:00003a39 r5:dcf89400
[  842.917896]  r4:00002300
[  842.917914] [<c0207e88>] (ext4_lazyinit_thread) from [<c0068334>] (kthread+0xd4/0xf0)
[  842.917922]  r10:00000000 r9:00000000 r8:00000000 r7:c0207e88 r6:dc1d38c0 r5:dd9c1b40
[  842.917943]  r4:00000000
[  842.917964] [<c0068260>] (kthread) from [<c000f698>] (ret_from_fork+0x14/0x20)
[  842.917971]  r7:00000000 r6:00000000 r5:c0068260 r4:dd9c1b40

**Comment by cyberb** [comment]
What about power source, do you have dedicated one for your drive?

**Comment by jpma89** [comment]
The affected drive is a 2,5" USB drive with no option to connect a dedicated power source and unfortunately I don't have a powered USB hub at hands.

My Beaglebone is connected to a 5V DC power supply. The USB disk was working fine for quite some time in the same setup.

**Comment by cyberb** [comment]
Log says it was running ext4lazyinit, do you have ext4 on this drive?

From google (https://www.thomas-krenn.com/en/wiki/Ext4_Filesystem) it is related to initial mount of newly formatted drive. You may follow some advices from the page to improve that.

I would still give it a try with usb power hub, I cannot really help with disk issues. Right now I do not even know if it is possible to ask disk if it has enough power for example. 

What we can do from our side is to provide more disk features like disk health check (smart utils).

**Comment by cyberb** [comment]
You could install smart tools:

````
apt-get install smartmontools
````

And run report on your drive so we can coompare

My report:
````
root@odroid-xu3:~# smartctl --all /dev/sda
smartctl 6.4 2014-10-07 r4002 [armv7l-linux-3.10.82] (local build)
Copyright (C) 2002-14, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Model Family:     Western Digital Elements / My Passport (USB, AF)
Device Model:     WDC WD20NMVW-11W68S0
Serial Number:    WD-WX21E42NX776
LU WWN Device Id: 5 0014ee 25cdd926e
Firmware Version: 01.01A01
User Capacity:    2,000,398,934,016 bytes [2.00 TB]
Sector Sizes:     512 bytes logical, 4096 bytes physical
Rotation Rate:    5200 rpm
Device is:        In smartctl database [for details use: -P show]
ATA Version is:   ATA8-ACS (minor revision not indicated)
SATA Version is:  SATA 3.0, 3.0 Gb/s (current: 3.0 Gb/s)
Local Time is:    Wed Dec  9 01:17:44 2015 UTC
SMART support is: Available - device has SMART capability.
SMART support is: Enabled

=== START OF READ SMART DATA SECTION ===
SMART Status not supported: Incomplete response, ATA output registers missing
SMART overall-health self-assessment test result: PASSED
Warning: This result is based on an Attribute check.

General SMART Values:
Offline data collection status:  (0x00)	Offline data collection activity
					was never started.
					Auto Offline Data Collection: Disabled.
Self-test execution status:      (   0)	The previous self-test routine completed
					without error or no self-test has ever 
					been run.
Total time to complete Offline 
data collection: 		(36360) seconds.
Offline data collection
capabilities: 			 (0x7b) SMART execute Offline immediate.
					Auto Offline data collection on/off support.
					Suspend Offline collection upon new
					command.
					Offline surface scan supported.
					Self-test supported.
					Conveyance Self-test supported.
					Selective Self-test supported.
SMART capabilities:            (0x0003)	Saves SMART data before entering
					power-saving mode.
					Supports SMART auto save timer.
Error logging capability:        (0x01)	Error logging supported.
					General Purpose Logging supported.
Short self-test routine 
recommended polling time: 	 (   2) minutes.
Extended self-test routine
recommended polling time: 	 ( 391) minutes.
Conveyance self-test routine
recommended polling time: 	 (   5) minutes.
SCT capabilities: 	       (0x70b5)	SCT Status supported.
					SCT Feature Control supported.
					SCT Data Table supported.

SMART Attributes Data Structure revision number: 16
Vendor Specific SMART Attributes with Thresholds:
ID# ATTRIBUTE_NAME          FLAG     VALUE WORST THRESH TYPE      UPDATED  WHEN_FAILED RAW_VALUE
  1 Raw_Read_Error_Rate     0x002f   200   200   051    Pre-fail  Always       -       0
  3 Spin_Up_Time            0x0027   211   206   021    Pre-fail  Always       -       4441
  4 Start_Stop_Count        0x0032   100   100   000    Old_age   Always       -       90
  5 Reallocated_Sector_Ct   0x0033   200   200   140    Pre-fail  Always       -       0
  7 Seek_Error_Rate         0x002e   100   253   000    Old_age   Always       -       0
  9 Power_On_Hours          0x0032   100   100   000    Old_age   Always       -       305
 10 Spin_Retry_Count        0x0032   100   253   000    Old_age   Always       -       0
 11 Calibration_Retry_Count 0x0032   100   253   000    Old_age   Always       -       0
 12 Power_Cycle_Count       0x0032   100   100   000    Old_age   Always       -       62
192 Power-Off_Retract_Count 0x0032   200   200   000    Old_age   Always       -       46
193 Load_Cycle_Count        0x0032   200   200   000    Old_age   Always       -       436
194 Temperature_Celsius     0x0022   116   111   000    Old_age   Always       -       36
196 Reallocated_Event_Count 0x0032   200   200   000    Old_age   Always       -       0
197 Current_Pending_Sector  0x0032   200   200   000    Old_age   Always       -       0
198 Offline_Uncorrectable   0x0030   100   253   000    Old_age   Offline      -       0
199 UDMA_CRC_Error_Count    0x0032   200   200   000    Old_age   Always       -       0
200 Multi_Zone_Error_Rate   0x0008   100   253   000    Old_age   Offline      -       0

SMART Error Log Version: 1
No Errors Logged

SMART Self-test log structure revision number 1
No self-tests have been logged.  [To run self-tests, use: smartctl -t]

SMART Selective self-test log data structure revision number 1
 SPAN  MIN_LBA  MAX_LBA  CURRENT_TEST_STATUS
    1        0        0  Not_testing
    2        0        0  Not_testing
    3        0        0  Not_testing
    4        0        0  Not_testing
    5        0        0  Not_testing
Selective self-test flags (0x0):
  After scanning selected spans, do NOT read-scan remainder of disk.
If Selective self-test is pending on power-up, resume after 0 minute delay.
````

**Comment by jpma89** [comment]
Short update on the issue:

Power supply is not the problem, but nonetheless it turned out that I can make sure the USB drive gets enough energy by setting the CPU frequency down.

For now it looks like there was some ext4 initialization issue. Not yet sure if solved. I will keep you updated.

**Comment by jpma89** [comment]
Still getting "Gateway timeout" as soon as the USB disk's led goes off. Looks like some false spindown /  power saving feature. Have tried to turn it off using hdparm, but no success so far.

**Comment by cyberb** [comment]
Glad that you have some progress!
You may build syncloud image based on another beagle bone black image if you want as we may have used non stable one.

Here is the image we are using:

https://github.com/syncloud/image/blob/master/extract/extract.sh#L35

Also we support setting cpu  frequencies per board (same file):
CPU_FREQUENCY_CONTROL=false
CPU_FREQUENCY_GOVERNOR=
CPU_FREQUENCY_MAX=
CPU_FREQUENCY_MIN=

Here is the instruction for building an image:

https://github.com/syncloud/image/blob/master/README.md

**Comment by cyberb** [comment]
Also looks like we are using beagle bone kernel from wheezy, maybe we should switch to jessie kernel from here:

https://rcn-ee.com/rootfs/bb.org/testing/2015-12-07/lxqt-4gb/bone-debian-8.2-lxqt-4gb-armhf-2015-12-07-4gb.img.xz

Do you want me to change our image to use that by default?

**Comment by jpma89** [comment]
Haven't been able to test Debian 8.2 yet, but sounds like a good approach the switch to the jessie kernel.

**Comment by cyberb** [comment]
I have updated BBB image to use 8.2: https://github.com/syncloud/image/commit/2d86a47ee937bcdbf2df3708784694a25615f344

Could you try latest image?
http://image.syncloud.org/1.0/syncloud-beagleboneblack-1.0.img.xz

**Comment by jpma89** [comment]
Short update:

The new jessie kernel seems to work fine, nothing suspicious with the new Debian version so far.

Regarding the issues: Stability (and ownCloud installation process) seems to be a bit improved when using following setup:
- CPU governor set to "powersave" on boot ==> 300 MHz most of the time :cry: 
- "hdparm -B 255 /dev/sda" on boot ==> forcing usb disk not to fall asleep
- usb disk is formatted as NTFS instead of ext4 ==> avoiding lazy ext4 init

Not done yet. I will keep you posted.

**Comment by cyberb** [comment]
We can Include frequencies into the image if that helps.
As well as no sleep for hdd I think.
As to non lazy, you can actually disable it during the format, for example:
mkfs.ext4 -E lazy_itable_init=0,lazy_journal_init=0 /dev/mapper/fc-root

Also I have just realized that kernel is even older in this BBB image from beaglebone.org: 3.14.22-ti-r31
dmesg you sent showed was 3.14.42-ti-r64

At the same time images from http://elinux.org/BeagleBoardDebian are all 4.* but they are single partitioned and we do not support that yet. So you may try it yourself, without syncloud on it, just to test hdd behaviour. And If you are happy with it I can do some work to automate them.

**Comment by jpma89** [comment]
Short update:
I tried an old 3.5" HDD with external power supply using ext4 without lazy init. No gateway timeouts or other issues at all. Maybe really a usb power issue. Strange thing is that with Syncloud 0.8 the same hardware setup was working fine.

Will try a newer kernel with my 2.5" drive as soon as possible.

**Comment by jpma89** [comment]
I've tested a BBB image with Debian 8.2 console and kernel 4.1.13-ti-r36. The HDD behaviour for the 2.5" USB drive looks pretty normal. Waking up the HDD from sleep works just fine.

I also compared the disk performance between the 2.5" and 3.5" drive. They seem to have kind of a comparable overall read/write performace as long as the 2.5" has enough power. If the power drops for some reason, the head drives back and the disk performance of course becomes very bad.

Let's put this issue as an hardware specific power supply issue and close it for now. I will try to get a powered USB hub or a better DC adapter for my BBB.
